// Dynamic asset loading for memetic-energy images
// The manifest is auto-generated by scripts/generate-meme-manifest.js
// To regenerate, run: npm run generate-meme-manifest
// This file is automatically updated when new assets are added

const HARDCODED_MANIFEST = {
  'Background': {
    '$CASHTAG': [
      '$BEPE.png',
      '$CASTER.png',
      '$CHIA.png',
      '$HOA.png',
      '$HONK.png',
      '$LOVE.png',
      '$NECKCOIN.png',
      '$PIZZA.png'
    ],
    'Plain Backgrounds': [
      'Chia Green.png',
      'Golden Hour.png',
      'Green Candle.png',
      'Hot Coral_.png',
      'Mellow Yellow.png',
      'Neo Mint.png',
      'Radioactive Forest.png',
      'Sky Dive.png',
      'Sky Shock Blue_.png',
      'Tangerine Pop_.png'
    ],
    'Scene': [
      'Bepe Barracks.png',
      'Chia Farm.png',
      'Hell.png',
      'Matrix.png',
      'MomΓÇÖs Basement.png',
      'Moon.png',
      'NYSE Dump.png',
      'NYSE Pump.png',
      'Nesting Grounds.png',
      'One Market.png',
      'Orange Grove.png',
      'Ronin Dojo.png',
      'Route 66.png',
      'Silicon.net Data Center.png',
      'Spell Room.png',
      'White House.png'
    ]
  },
  'Base': {
    '': [
      'BASE_Wojak_Bepe Army.png',
      'BASE_Wojak_Born to Ride.png',
      'BASE_Wojak_Chia Farmer.png',
      'BASE_Wojak_El Presidente.png',
      'BASE_Wojak_Leather Jacket.png',
      'BASE_Wojak_Ninja Turtle.png',
      'BASE_Wojak_Ronin.png',
      'BASE_Wojak_SWAT Gear.png',
      'BASE_Wojak_Sports Jacket.png',
      'BASE_Wojak_Tee_blue.png',
      'BASE_Wojak_Tee_orange.png',
      'BASE_Wojak_Topless.png',
      'BASE_Wojak_Wizard Fit_blue.png',
      'BASE_Wojak_Wizard Fit_orange.png',
      'BASE_Wojak_Wizard Fit_purple.png'
    ]
  },
  'Eyes': {
    '': [
      'EYES_Green laser.png',
      'EYES_Ninja Turtle mask.png',
      'EYES_Shades_.png',
      'EYE_3D Glasses_.png',
      'EYE_Alpha Shades_.png',
      'EYE_Aviators_.png',
      'EYE_Cyber Shades_.png',
      'EYE_Cyber Shades_black.png',
      'EYE_Eye Patch_.png',
      'EYE_MOG Glasses.png',
      'EYE_Matrix Lenses_.png',
      'EYE_Night Vision_.png',
      'EYE_Tyson Tattoo_.png',
      'EYE_VR Headset_.png',
      'EYE_VR Headset_staker.png',
      'EYE_Wizard Glasses_NEW.png',
      'Eye_Cool Glasses_.png'
    ]
  },
  'Head': {
    '': [
      'HEAD_2Pac Bandana_.png',
      'HEAD_Beanie_.png',
      'HEAD_Cap_Chia.png',
      'HEAD_Cap_McD.png',
      'HEAD_Centurion_.png',
      'HEAD_Clown_.png',
      'HEAD_Comrade Cap_.png',
      'HEAD_Construction Helmet_.png',
      'HEAD_Cowboy Hat_.png',
      'HEAD_Crown_.png',
      'HEAD_Devil Horns.png',
      'HEAD_Fedora_Orange.png',
      'HEAD_Fedora_Purple.png',
      'HEAD_Field Cap_.png',
      'HEAD_Firefigther Helmet_.png',
      'HEAD_Hard Hat_.png',
      'HEAD_Headphones_.png',
      'HEAD_Military Beret_.png',
      'HEAD_Piccolo Hat_.png',
      'HEAD_Propeller Hat_.png',
      'HEAD_Ronin Helmet.png',
      'HEAD_SWAT Helmet.png',
      'HEAD_Super Mario Luigi_.png',
      'HEAD_Super Mario_.png',
      'HEAD_Super Saiyan_.png',
      'HEAD_Tin Foil_.png',
      'HEAD_Trump Wave_.png',
      'HEAD_Vikings Hat_.png',
      'HEAD_Wizard Hat_orange.png',
      'HEAD_Wizard Hat_pink.png',
      'HEAD_Wizard Hat_red.png'
    ]
  },
  'Mouth': {
    '': [
      'MOUTH_Bandana Mask_.png',
      'MOUTH_Bubble Gum_.png',
      'MOUTH_Cig_.png',
      'MOUTH_Cohiba_.png',
      'MOUTH_Copium Mask.png',
      'MOUTH_Drac teeth.png',
      'MOUTH_Gold Teeth.png',
      'MOUTH_Hannibal Mask.png',
      'MOUTH_Joint_.png',
      'MOUTH_Neckbeards_black.png',
      'MOUTH_Neckbeards_grey.png',
      'MOUTH_Numb.png',
      'MOUTH_Pipe.png',
      'MOUTH_Pizza.png',
      'MOUTH_Screeming.png',
      'MOUTH_Smile.png',
      'MOUTH_Stach.png',
      'MOUTH_Teeth.png'
    ]
  }
}

// Use the manifest (auto-generated by script)
const MANIFEST = HARDCODED_MANIFEST

// Helper function to clean display names
function cleanDisplayName(fileName, layerName) {
  const name = fileName.replace('.png', '')
  return name
    .replace(/BASE_Wojak_/g, '')
    .replace(/BASE_Base-Wojak_/g, '')
    .replace(/BACKGROUND_/g, '')
    .replace(/CLOTHES_/g, '')
    .replace(/EXTRA_/g, '')
    .replace(/EXTRA-on-tee,tank-top_CLOTHES_/g, '')
    .replace(/EYE_|EYES_/g, '')
    .replace(/HEAD_/g, '')
    .replace(/MOUTH_/g, '')
    .replace(/_/g, ' ')
    .replace(/-/g, ' ')
    .trim()
}

// Helper function to get image path
function getImagePath(layerName, subfolder, fileName) {
  // Use /memetic-energy/ path (actual folder structure)
  const path = subfolder 
    ? `/memetic-energy/${layerName}/${subfolder}/${fileName}`
    : `/memetic-energy/${layerName}/${fileName}`
  return path
}

export function getLayerImagesBySubfolder(layerName) {
  const layerData = MANIFEST[layerName]
  if (!layerData) return {}

  const organized = {}
  
  Object.keys(layerData).forEach(subfolder => {
    const files = layerData[subfolder]
    organized[subfolder] = files.map(fileName => {
      const name = fileName.replace('.png', '')
      const fullName = subfolder ? `${subfolder}/${name}` : name
      const path = getImagePath(layerName, subfolder, fileName)
      
      return {
        name,
        fullName,
        path,
        displayName: cleanDisplayName(fileName, layerName)
      }
    })
  })

  return organized
}

/**
 * Get all images from a layer, flattened (no subfolder organization)
 * @param {string} layerName - Name of the layer (Background, Base, Eyes, etc.)
 * @returns {Array} Array of image objects with name, path, and displayName
 */
export function getAllLayerImages(layerName) {
  const layerData = MANIFEST[layerName]
  if (!layerData) return []

  const allImages = []
  
  Object.keys(layerData).forEach(subfolder => {
    const files = layerData[subfolder]
    files.forEach(fileName => {
      const name = fileName.replace('.png', '')
      const path = getImagePath(layerName, subfolder, fileName)
      
      allImages.push({
        name,
        path,
        displayName: cleanDisplayName(fileName, layerName)
      })
    })
  })

  return allImages
}
