// Dynamic asset loading for wojak-creator images
// The manifest is auto-generated by scripts/generate-meme-manifest.js
// To regenerate, run: npm run generate-meme-manifest
// This file is automatically updated when new assets are added

const HARDCODED_MANIFEST = {
  'Background': {
    '$CASHTAG': [
      'BACKGROUND_$BEPE.png',
      'BACKGROUND_$CASTER.png',
      'BACKGROUND_$CHIA.png',
      'BACKGROUND_$HOA.png',
      'BACKGROUND_$HONK.png',
      'BACKGROUND_$LOVE.png',
      'BACKGROUND_$NECKCOIN.png',
      'BACKGROUND_$PIZZA.png'
    ],
    'Plain Backgrounds': [
      'BACKGROUND_Chia Green.png',
      'BACKGROUND_Golden Hour.png',
      'BACKGROUND_Green Candle.png',
      'BACKGROUND_Hot Coral_.png',
      'BACKGROUND_Mellow Yellow.png',
      'BACKGROUND_Neo Mint.png',
      'BACKGROUND_Radioactive Forest.png',
      'BACKGROUND_Sky Dive.png',
      'BACKGROUND_Sky Shock Blue_.png',
      'BACKGROUND_Tangerine Pop_.png'
    ],
    'Scene': [
      'BACKGROUND_Bepe Barracks.png',
      'BACKGROUND_Chia Farm.png',
      'BACKGROUND_Hell.png',
      'BACKGROUND_Matrix.png',
      'BACKGROUND_MomΓÇÖs Basement.png',
      'BACKGROUND_Moon.png',
      'BACKGROUND_NYSE Dump.png',
      'BACKGROUND_NYSE Pump.png',
      'BACKGROUND_Nesting Grounds.png',
      'BACKGROUND_One Market.png',
      'BACKGROUND_Orange Grove.png',
      'BACKGROUND_Ronin Dojo.png',
      'BACKGROUND_Route 66.png',
      'BACKGROUND_Silicon.net Data Center.png',
      'BACKGROUND_Spell Room.png',
      'BACKGROUND_White House.png'
    ]
  },
  'Base': {
    '': [
      'BASE_Base-Wojak_bleeding-bags.png',
      'BASE_Base-Wojak_classic.png',
      'BASE_Base-Wojak_rekt.png',
      'BASE_Base-Wojak_rugged.png',
      'BASE_Base-Wojak_terminator.png'
    ]
  },
  'Clothes': {
    '': [
      'CLOTHES_Astronaut_.png',
      'CLOTHES_Bathrobe_black.png',
      'CLOTHES_Bathrobe_blue.png',
      'CLOTHES_Bathrobe_red.png',
      'CLOTHES_Bepe-Army_.png',
      'CLOTHES_Born-to-Ride_.png',
      'CLOTHES_Firefigther-Uniform_.png',
      'CLOTHES_Leather-Jacket_.png',
      'CLOTHES_Military-Jacket.png',
      'CLOTHES_Roman-Drip_.png',
      'CLOTHES_Ronin.png',
      'CLOTHES_SWAT-Gear-.png',
      'CLOTHES_Sports-Jacket_blue.png',
      'CLOTHES_Sports-Jacket_green.png',
      'CLOTHES_Sports-Jacket_orange.png',
      'CLOTHES_Sports-Jacket_red.png',
      'CLOTHES_Straitjacket_.png',
      'CLOTHES_Suit_black_blue-tie.png',
      'CLOTHES_Suit_black_pink-tie.png',
      'CLOTHES_Suit_black_red-bow.png',
      'CLOTHES_Suit_black_red-tie.png',
      'CLOTHES_Suit_black_yellow-bow.png',
      'CLOTHES_Suit_orange_blue-tie.png',
      'CLOTHES_Suit_orange_pink-tie.png',
      'CLOTHES_Suit_orange_red-bow.png',
      'CLOTHES_Suit_orange_red-tie.png',
      'CLOTHES_Suit_orange_yellow-bow.png',
      'CLOTHES_Super-Saiyan_.png',
      'CLOTHES_Tank-Top_Neon-Green.png',
      'CLOTHES_Tank-Top_blue.png',
      'CLOTHES_Tank-Top_orange.png',
      'CLOTHES_Tank-Top_red.png',
      'CLOTHES_Tee_blue.png',
      'CLOTHES_Tee_orange.png',
      'CLOTHES_Tee_red.png',
      'CLOTHES_Topless_.png',
      'CLOTHES_Topless_blue.png',
      'CLOTHES_Viking-Armor.png',
      'CLOTHES_Wizard-Drip_blue.png',
      'CLOTHES_Wizard-Drip_orange.png',
      'CLOTHES_Wizard-Drip_pink.png',
      'CLOTHES_Wizard-Drip_purple.png',
      'CLOTHES_Wizard-Drip_red.png',
      'CLOTHES_god-rope.png'
    ]
  },
  'Eyes': {
    '': [
      'EYE_3D-Glasses_.png',
      'EYE_Alpha-Shades_blue.png',
      'EYE_Alpha-Shades_pink.png',
      'EYE_Alpha-Shades_red.png',
      'EYE_Aviators_.png',
      'EYE_Cool-Glasses_.png',
      'EYE_Cyber-Shades_black.png',
      'EYE_Cyber-Shades_purple.png',
      'EYE_Eye-Patch_.png',
      'EYE_Laser-Eyes_green.png',
      'EYE_Laser-Eyes_red.png',
      'EYE_MOG-Glasses.png',
      'EYE_Matrix-Lenses_red.png',
      'EYE_Ninja-Turtle-mask.png',
      'EYE_Shades_blue.png',
      'EYE_Shades_neon-green.png',
      'EYE_Shades_red.png',
      'EYE_Tyson-Tattoo_.png',
      'EYE_Wizard-Glasses_.png',
      'EYE_Wizard-Glasses_NEW.png'
    ]
  },
  'Head': {
    '': [
      'HEAD_2Pac-Bandana_pink.png',
      'HEAD_2Pac-Bandana_red.png',
      'HEAD_Anarchy-Spikes_pink.png',
      'HEAD_Anarchy-Spikes_red.png',
      'HEAD_Beanie_.png',
      'HEAD_Cap_McD.png',
      'HEAD_Cap_blue.png',
      'HEAD_Cap_green.png',
      'HEAD_Cap_orange.png',
      'HEAD_Centurion_.png',
      'HEAD_Centurion_mask.png',
      'HEAD_Clown_.png',
      'HEAD_Comrade-Cap_.png',
      'HEAD_Construction-Helmet_.png',
      'HEAD_Cowboy-Hat_.png',
      'HEAD_Cowboy-Hat_brown.png',
      'HEAD_Crown_.png',
      'HEAD_Devil-Horns.png',
      'HEAD_Fedora_brown.png',
      'HEAD_Fedora_orange.png',
      'HEAD_Fedora_purple.png',
      'HEAD_Field-Cap_.png',
      'HEAD_Firefigther-Helmet_.png',
      'HEAD_Hard-Hat_.png',
      'HEAD_Headphones_.png',
      'HEAD_Military-Beret.png',
      'HEAD_Piccolo-Hat_.png',
      'HEAD_Pirate-Hat_.png',
      'HEAD_Propeller-Hat_.png',
      'HEAD_Ronin-Helmet.png',
      'HEAD_SWAT-Helmet.png',
      'HEAD_Standard-Cut_blond.png',
      'HEAD_Standard-Cut_brown.png',
      'HEAD_Super-Mario_green.png',
      'HEAD_Super-Mario_purple.png',
      'HEAD_Super-Mario_red.png',
      'HEAD_Super-Saiyan.png',
      'HEAD_Tin-Foil_.png',
      'HEAD_Trump-Wave_.png',
      'HEAD_Vikings-Hat_.png',
      'HEAD_Wizard-Hat_man.png',
      'HEAD_Wizard-Hat_man_blue.png',
      'HEAD_Wizard-Hat_man_green.png',
      'HEAD_Wizard-Hat_man_pink.png',
      'HEAD_Wizard-Hat_man_purple.png',
      'HEAD_Wizard-Hat_man_red.png'
    ]
  },
  'Mouth': {
    '': [
      'MOUTH_Bandana-Mask_.png',
      'MOUTH_Bubble-Gum_.png',
      'MOUTH_Bubble-Gum_rekt.png',
      'MOUTH_Gold-Teeth.png',
      'MOUTH_Hannibal-Mask.png',
      'MOUTH_Pipe.png',
      'MOUTH_Pizza.png',
      'MOUTH_Teeth.png',
      'MOUTH_numb.png',
      'MOUTH_screeming.png',
      'MOUTH_smile.png'
    ]
  },
  'Extra': {
    '': [
      'EXTRA-on-tee,tank-top_CLOTHES_Chia-Farmer_blue.png',
      'EXTRA-on-tee,tank-top_CLOTHES_Chia-Farmer_brown.png',
      'EXTRA-on-tee,tank-top_CLOTHES_Chia-Farmer_orange.png',
      'EXTRA-on-tee,tank-top_CLOTHES_Chia-Farmer_red.png',
      'EXTRA_MOUTH_Cig_.png',
      'EXTRA_MOUTH_Cohiba_.png',
      'EXTRA_MOUTH_Copium-Mask.png',
      'EXTRA_MOUTH_Joint_.png',
      'EXTRA_MOUTH_Neckbeard_.png',
      'EXTRA_MOUTH_stach.png'
    ]
  },
  'MouthBase': {
    '': [
      'MOUTH_Bubble-Gum_.png',
      'MOUTH_Gold-Teeth.png',
      'MOUTH_Pipe.png',
      'MOUTH_Pizza.png',
      'MOUTH_Teeth.png',
      'MOUTH_numb.png',
      'MOUTH_screeming.png',
      'MOUTH_smile.png'
    ]
  },
  'MouthItem': {
    '': [
      'EXTRA_MOUTH_Cig_.png',
      'EXTRA_MOUTH_Cohiba_.png',
      'EXTRA_MOUTH_Joint_.png'
    ]
  },
  'FacialHair': {
    '': [
      'EXTRA_MOUTH_Neckbeard_.png',
      'EXTRA_MOUTH_stach.png'
    ]
  },
  'Mask': {
    '': [
      'EXTRA_MOUTH_Copium-Mask.png',
      'MOUTH_Bandana-Mask_.png',
      'MOUTH_Hannibal-Mask.png'
    ]
  },
  'ClothesAddon': {
    '': [
      'EXTRA-on-tee,tank-top_CLOTHES_Chia-Farmer_blue.png',
      'EXTRA-on-tee,tank-top_CLOTHES_Chia-Farmer_brown.png',
      'EXTRA-on-tee,tank-top_CLOTHES_Chia-Farmer_orange.png',
      'EXTRA-on-tee,tank-top_CLOTHES_Chia-Farmer_red.png'
    ]
  }
}

// Use the manifest (auto-generated by script)
const MANIFEST = HARDCODED_MANIFEST

// Helper function to clean display names
function cleanDisplayName(fileName, layerName) {
  const name = fileName.replace('.png', '')
  return name
    .replace(/BASE_Wojak_/g, '')
    .replace(/BASE_Base-Wojak_/g, '')
    .replace(/BACKGROUND_/g, '')
    .replace(/CLOTHES_/g, '')
    .replace(/EXTRA_/g, '')
    .replace(/EXTRA-on-tee,tank-top_CLOTHES_/g, '')
    .replace(/EYE_|EYES_/g, '')
    .replace(/HEAD_/g, '')
    .replace(/MOUTH_/g, '')
    .replace(/_/g, ' ')
    .replace(/-/g, ' ')
    .trim()
}

// Map layer names back to folder names for paths
// For virtual layers, map to their source folders
const LAYER_TO_FOLDER_MAP = {
  'Background': 'BACKGROUND',
  'Base': 'BASE',
  'Clothes': 'CLOTHES',
  'ClothesAddon': 'EXTRA', // Virtual layer from EXTRA
  'Eyes': 'EYE',
  'Head': 'HEAD',
  'MouthBase': 'MOUTH', // Virtual layer from MOUTH
  'MouthItem': 'MOUTH', // Virtual layer from MOUTH and EXTRA
  'FacialHair': 'EXTRA', // Virtual layer from EXTRA
  'Mask': 'MOUTH', // Virtual layer from MOUTH and EXTRA
  'Mouth': 'MOUTH', // Legacy
  'Extra': 'EXTRA', // Legacy
}

// Map for virtual layers that need to check multiple source folders
const VIRTUAL_LAYER_SOURCES = {
  'MouthItem': ['MOUTH', 'EXTRA'],
  'Mask': ['MOUTH', 'EXTRA'],
}

// Helper function to get image path
function getImagePath(layerName, subfolder, fileName) {
  // Use /wojak-creator/ path (actual folder structure)
  // Convert layer name to folder name
  let folderName = LAYER_TO_FOLDER_MAP[layerName] || layerName
  
  // For virtual layers with multiple sources, determine which folder based on file prefix
  if (VIRTUAL_LAYER_SOURCES[layerName]) {
    // Files from EXTRA typically have EXTRA_ prefix
    if (fileName.startsWith('EXTRA_')) {
      folderName = 'EXTRA'
    } else {
      // Default to the primary source folder
      folderName = LAYER_TO_FOLDER_MAP[layerName] || 'MOUTH'
    }
  }
  
  const path = subfolder 
    ? `/wojak-creator/${folderName}/${subfolder}/${fileName}`
    : `/wojak-creator/${folderName}/${fileName}`
  return path
}

export function getLayerImagesBySubfolder(layerName) {
  const layerData = MANIFEST[layerName]
  if (!layerData) return {}

  const organized = {}
  
  Object.keys(layerData).forEach(subfolder => {
    const files = layerData[subfolder]
    organized[subfolder] = files.map(fileName => {
      const name = fileName.replace('.png', '')
      const fullName = subfolder ? `${subfolder}/${name}` : name
      const path = getImagePath(layerName, subfolder, fileName)
      
      return {
        name,
        fullName,
        path,
        displayName: cleanDisplayName(fileName, layerName)
      }
    })
  })

  return organized
}

/**
 * Get all images from a layer, flattened (no subfolder organization)
 * @param {string} layerName - Name of the layer (Background, Base, Eyes, etc.)
 * @returns {Array} Array of image objects with name, path, and displayName
 */
export function getAllLayerImages(layerName) {
  const layerData = MANIFEST[layerName]
  if (!layerData) return []

  const allImages = []
  
  Object.keys(layerData).forEach(subfolder => {
    const files = layerData[subfolder]
    files.forEach(fileName => {
      const name = fileName.replace('.png', '')
      const path = getImagePath(layerName, subfolder, fileName)
      
      allImages.push({
        name,
        path,
        displayName: cleanDisplayName(fileName, layerName)
      })
    })
  })

  return allImages
}
