import type { AICategory, AIStyleFamily, AICategoryPresets } from '@/types/aiEnhance';

// --- Universal Enhance Families (shared across clothes and head) ---

const UNIVERSAL_ENHANCE: AIStyleFamily[] = [
  {
    label: '🐾 Animal Prints',
    options: [
      { label: 'Tiger stripes', prompt: 'Add bold tiger stripe pattern, dark brown and black stripes on orange-tan base, natural animal fur texture' },
      { label: 'Leopard spots', prompt: 'Apply leopard spot pattern with golden tan rosettes and dark brown spots, exotic animal print' },
      { label: 'Zebra stripes', prompt: 'Add black and white zebra stripe pattern, bold contrasting parallel lines, African wildlife print' },
      { label: 'Snake skin', prompt: 'Apply reptile snake skin texture with diamond-shaped scales, iridescent green and brown pattern' },
      { label: 'Cow print', prompt: 'Add black and white cow spot pattern, large irregular patches, Holstein dairy cow print' },
      { label: 'Cheetah dots', prompt: 'Add cheetah spot pattern with small solid black dots on golden-tan base, fastest animal print' },
      { label: 'Dalmatian spots', prompt: 'Apply black dalmatian spot pattern on white base, round irregular dots, classic dog breed print' },
      { label: 'Shark skin', prompt: 'Apply shark skin texture with fine overlapping dermal denticles, slate blue-grey smooth scale pattern' },
      { label: 'Peacock feather', prompt: 'Apply iridescent peacock feather eye pattern, deep blue-green with golden rings, exotic bird plumage' },
      { label: 'Wolf grey fur', prompt: 'Apply wolf fur texture with layered grey guard hairs and darker dorsal stripe, wild canine coat' },
      { label: 'Flamingo pink', prompt: 'Apply flamingo feather texture in vivid tropical pink, soft layered plumage, wading bird coloring' },
    ],
  },
  {
    label: '🔥 Elemental',
    options: [
      { label: 'Flame pattern', prompt: 'Add bold orange and red flame pattern, realistic fire texture with hot orange tips fading to deep red' },
      { label: 'Ice frost', prompt: 'Cover with ice crystals and frost, thin frozen layer, cool blue-white crystalline frozen surface' },
      { label: 'Lightning bolts', prompt: 'Add bright yellow-white lightning bolt streaks crackling across the surface, electric energy effect' },
      { label: 'Lava cracks', prompt: 'Add deep cracks with bright orange-red molten lava glowing through, dark volcanic rock surface with magma veins' },
      { label: 'Smoke & ash', prompt: 'Cover with grey smoke wisps and dark ash residue, smoldering charred look, burnt smoky effect' },
      { label: 'Tidal wave splash', prompt: 'Cover with crashing ocean wave splash, foamy white sea water drenching the surface, deep blue tidal power' },
      { label: 'Arctic blizzard', prompt: 'Blast with arctic blizzard snow, horizontal driving white snowflakes, ice crystals encrusting the surface' },
      { label: 'Solar flare scorch', prompt: 'Scorch with intense solar flare energy, glowing white-orange burned patches, intense heat radiation damage' },
      { label: 'Swamp murk', prompt: 'Cover with dark swamp murk and algae, slimy greenish-brown bog water coating, fetid wetland texture' },
      { label: 'Meteor impact burn', prompt: 'Scorch with meteor impact damage, radiating burn marks from center, blackened char with glowing orange edges' },
      { label: 'Static electricity', prompt: 'Charge with static electricity, hair-raising crackling charge, pale blue static sparks and prickling energy' },
    ],
  },
  {
    label: '✨ Precious Metals',
    options: [
      { label: 'Gold plating', prompt: 'Cover with polished gold plating, reflective metallic gold surface with subtle shine highlights, luxury gold finish' },
      { label: 'Chrome mirror', prompt: 'Transform into polished chrome with mirror-like reflective surface, sleek liquid metal silver finish' },
      { label: 'Diamond encrusted', prompt: 'Cover with small embedded diamonds and gemstones, sparkling crystal studs, encrusted jewelry bling effect' },
      { label: 'Copper patina', prompt: 'Apply aged copper finish with green patina oxidation, weathered bronze-green metallic surface' },
      { label: 'Obsidian black glass', prompt: 'Transform into smooth glossy obsidian volcanic glass, deep black reflective surface with sharp edges' },
      { label: 'Brushed titanium', prompt: 'Apply brushed titanium matte grey metallic finish, fine directional scratches on metal, industrial premium look' },
      { label: 'Rose gold', prompt: 'Apply warm rose gold metallic finish, pinkish-gold sheen with soft warm reflections, luxury jewelry aesthetic' },
      { label: 'Molten silver', prompt: 'Cover with flowing molten silver liquid metal, bright mercury-like reflective surface dripping and pooling' },
      { label: 'Bronze casting', prompt: 'Transform into solid bronze cast metal, warm yellow-brown metallic color with classical sculpture finish' },
      { label: 'Iron forge', prompt: 'Apply dark iron forge metal texture, rough hammer-worked surface, freshly smithed dark grey metal' },
      { label: 'Iridescent opal', prompt: 'Apply opal gem effect with shifting rainbow color play, milky white base with rainbow fire flashes' },
      { label: 'Mithril weave', prompt: 'Apply mithril fantasy metal look, glowing silver-blue magical alloy with ethereal inner luminescence' },
    ],
  },
  {
    label: '⚔️ Battle Worn',
    options: [
      { label: 'Dented & scratched', prompt: 'Add battle damage with visible dents, deep scratches, and worn surface, weathered from combat' },
      { label: 'Rusty corroded', prompt: 'Transform with orange-brown rust spots, patchy oxidation, weathered corroded metal texture' },
      { label: 'Arrow pierced', prompt: 'Add an arrow stuck through the surface, wooden shaft and feathered fletching, battle damage' },
      { label: 'Blood splattered', prompt: 'Add dark red blood splatter marks and drips across the surface, battle-stained and gory' },
      { label: 'Wrapped in bandages', prompt: 'Wrap with torn white cloth bandages and medical tape, combat field repair look' },
      { label: 'Cracked with light leaking', prompt: 'Add deep cracks across the surface with bright golden-white light glowing through from inside' },
      { label: 'Charred & burned', prompt: 'Blacken and char the surface from intense fire, carbon-black scorched texture with flaking burnt material' },
      { label: 'Bullet holes', prompt: 'Punch clean bullet holes through the surface, multiple impact craters with radiating cracks, gunshot damage' },
      { label: 'Explosion blast marks', prompt: 'Add black explosion scorch marks radiating from an impact point, shrapnel pits, blast wave damage' },
      { label: 'Chain wrapped', prompt: 'Bind with heavy iron chains wrapped tightly around, chain link impressions and iron rust stains' },
      { label: 'War-painted', prompt: 'Smear with primal war paint in red and black, tribal warrior face and body marking stripes' },
    ],
  },
  {
    label: '🎨 Art & Paint',
    options: [
      { label: 'Graffiti spray', prompt: 'Cover with colorful graffiti spray paint, bold dripping letters and tags, urban street art style' },
      { label: 'Splatter paint', prompt: 'Cover with Jackson Pollock style paint splatters, random drips and splashes in multiple bright colors' },
      { label: 'Watercolor wash', prompt: 'Apply soft watercolor paint wash effect, translucent bleeding colors, artistic wet paint look' },
      { label: 'Neon paint', prompt: 'Cover with bright fluorescent neon paint in pink, green, and yellow, glowing blacklight reactive colors' },
      { label: 'Comic halftone dots', prompt: 'Apply comic book halftone dot pattern, Ben-Day dots in pop art style, Roy Lichtenstein effect' },
      { label: 'Stained glass mosaic', prompt: 'Transform into stained glass mosaic pattern with black lead lines between colorful translucent glass segments' },
      { label: 'Ink brush strokes', prompt: 'Apply bold East Asian ink brush strokes, flowing sumi-e style black ink on white, calligraphy art' },
      { label: 'Oil painting impasto', prompt: 'Apply thick impasto oil paint with visible palette knife ridges and brushstroke texture, fine art painting' },
      { label: 'Chalk pastel', prompt: 'Apply soft chalk pastel texture with smudgy blended colors, dusty powdery surface, street chalk art' },
      { label: 'Mosaic tiles', prompt: 'Transform into small ceramic mosaic tiles with grout lines between colorful hand-painted squares, Byzantine art' },
      { label: 'Woodblock print', prompt: 'Apply Japanese ukiyo-e woodblock print style, flat color areas with visible ink grain, Hokusai aesthetic' },
    ],
  },
  {
    label: '👾 Digital & Glitch',
    options: [
      { label: '8-bit pixelated', prompt: 'Transform into chunky 8-bit pixel art style, blocky retro video game graphics, low-resolution mosaic' },
      { label: 'Glitch artifact', prompt: 'Add digital glitch effects with horizontal scan lines, data corruption artifacts, distorted pixel blocks' },
      { label: 'VHS distortion', prompt: 'Apply VHS tape distortion with tracking lines, color bleeding, analog video noise and static' },
      { label: 'Circuit board', prompt: 'Transform surface into green circuit board PCB with copper traces, solder points, and microchip components' },
      { label: 'Hologram flicker', prompt: 'Add holographic projection effect with blue transparent overlay, scan lines, and digital flicker' },
      { label: 'RGB chromatic split', prompt: 'Apply RGB color channel split effect, offset red green and blue layers creating triple-vision glitch' },
      { label: 'Binary rain', prompt: 'Cover with falling binary 0s and 1s in bright green on dark background, digital code data stream' },
      { label: 'Pixel sort', prompt: 'Apply pixel sorting glitch art effect, columns of pixels sorted by brightness creating streaked distortion' },
      { label: 'Low poly mesh', prompt: 'Transform into low polygon 3D mesh, geometric triangular facets with flat shading, game asset style' },
      { label: 'ASCII art', prompt: 'Transform into ASCII character art, the image rendered in typed text characters, computer terminal style' },
      { label: 'Neon wireframe', prompt: 'Convert to glowing neon wireframe outline, bright edge lines on dark void, vector grid aesthetic' },
    ],
  },
  {
    label: '🌿 Nature Overgrowth',
    options: [
      { label: 'Ivy vines', prompt: 'Add green ivy vines and small leaves growing across the surface, nature reclaiming with organic tendrils' },
      { label: 'Moss covered', prompt: 'Cover with soft green moss patches, damp fuzzy lichen growing on the surface, ancient overgrown look' },
      { label: 'Flower blooms', prompt: 'Add colorful flowers blooming from the surface, roses daisies and wildflowers sprouting organically' },
      { label: 'Coral growth', prompt: 'Add underwater coral formations growing on surface, pink and orange brain coral and sea anemones' },
      { label: 'Mushroom sprouts', prompt: 'Add small mushrooms and toadstools sprouting from the surface, fantasy fungal growth, colorful caps' },
      { label: 'Bird nest', prompt: 'Add a small bird nest with twigs and straw nestled on the surface, cozy natural wildlife home' },
      { label: 'Seaweed wrap', prompt: 'Drape with dark green seaweed strands, wet ocean kelp draped across the surface, washed ashore look' },
      { label: 'Tree bark overlay', prompt: 'Transform surface into rough tree bark texture, deep vertical fissures and ridges, ancient oak bark' },
      { label: 'Web of roots', prompt: 'Wrap with tangled tree roots growing across the surface, knotted woody tendrils, underground forest root system' },
      { label: 'Firefly glow', prompt: 'Surround with floating firefly bioluminescence, dozens of tiny glowing yellow-green light orbs drifting' },
      { label: 'Autumn leaves', prompt: 'Cover with fallen autumn leaves in red orange and yellow, dry crinkled maple leaves scattered across' },
      { label: 'Honey drip', prompt: 'Drizzle with golden honey, thick amber liquid dripping and pooling, beehive sweetness coating' },
    ],
  },
];

// --- Clothes-Only Enhance Families ---

const CLOTHES_ENHANCE: AIStyleFamily[] = [
  {
    label: '💎 Luxury & Bling',
    options: [
      { label: 'Gold embroidery', prompt: 'Add intricate gold thread embroidery with ornate swirl patterns and decorative stitching, metallic gold on fabric' },
      { label: 'Diamond studs', prompt: 'Add sparkling diamond studs scattered across the clothing, small clear crystals catching light, bling effect' },
      { label: 'Velvet texture', prompt: 'Transform the fabric into rich deep velvet with soft plush pile texture, luxurious smooth finish' },
      { label: 'Fur trim', prompt: 'Add soft fur trim along edges and collar, fluffy animal fur border in warm brown, luxury winter look' },
      { label: 'Sequin sparkle', prompt: 'Cover with round sequin discs catching light, thousands of small reflective circles, sparkling disco fabric' },
      { label: 'Silk satin sheen', prompt: 'Transform into smooth silk satin fabric with glossy reflective sheen, elegant draping material' },
      { label: 'Gold chain drape', prompt: 'Drape thick gold chains across the chest and shoulders, layered heavy gold links, hip-hop bling style' },
      { label: 'Ruby encrusted', prompt: 'Stud with large deep red rubies set in gold bezels across the fabric, royal jeweled garment' },
      { label: 'Brocade tapestry', prompt: 'Transform into richly woven brocade tapestry fabric with raised gold and silver thread floral patterns' },
      { label: 'Lace overlay', prompt: 'Layer delicate white lace overlay across the clothing, intricate floral needle lace pattern, bridal luxury' },
      { label: 'Pearl strand draped', prompt: 'Drape multiple strands of lustrous pearls across the clothing, classic pearl necklace layers, old money elegance' },
    ],
  },
  {
    label: '🎖️ Tactical & Combat',
    options: [
      { label: 'Woodland camo', prompt: 'Apply military camouflage pattern with olive green, dark brown, tan, and black irregular patches, woodland camo' },
      { label: 'Desert camo', prompt: 'Apply desert camouflage pattern with tan, beige, brown, and khaki irregular patches, arid sand camo' },
      { label: 'Tactical vest webbing', prompt: 'Add MOLLE tactical vest webbing straps and pouches over the clothing, military load-bearing gear' },
      { label: 'Ammunition belt wraps', prompt: 'Wrap ammunition belts across the clothing, brass bullet rounds in canvas belt, action hero look' },
      { label: 'Military medal patches', prompt: 'Add military rank patches, merit badges, and medal ribbons pinned to the chest area' },
      { label: 'Dog tag chains', prompt: 'Add metal military dog tags on ball chain necklace hanging over the clothing, soldier identity tags' },
      { label: 'Urban camo city', prompt: 'Apply urban warfare camouflage with grey, black, and white city building shapes, metropolitan camo pattern' },
      { label: 'Ghillie suit foliage', prompt: 'Transform into a sniper ghillie suit covered in shredded green and brown foliage strips, disappear in nature' },
      { label: 'Tactical plate carrier', prompt: 'Add modern plate carrier body armor over the shirt, hard ballistic panels with cummerbund straps, SWAT gear' },
      { label: 'Subdued flag patches', prompt: 'Add subdued IR flag patches and unit identifier patches on the sleeves and chest, spec ops uniform' },
      { label: 'Multicam pattern', prompt: 'Apply MultiCam transitional camouflage in tan and green, US Army OCP pattern, Afghanistan operational camo' },
    ],
  },
  {
    label: '🎸 Street & Punk',
    options: [
      { label: 'Punk patches', prompt: 'Add punk rock patches, band logos sewn on fabric, DIY rebellious punk aesthetic' },
      { label: 'Graffiti paint', prompt: 'Spray paint colorful graffiti tags and throw-ups across the fabric, street art style' },
      { label: 'Torn distressed', prompt: 'Add torn rips and distressed holes in the fabric, frayed edges, worn grunge look' },
      { label: 'Safety pins & studs', prompt: 'Add safety pins, metal cone studs, and rivets pierced through the fabric, punk DIY style' },
      { label: 'Studded leather', prompt: 'Transform into black studded leather with rows of metal dome studs, biker punk aesthetic' },
      { label: 'Skateboard graphics', prompt: 'Add bold skateboard deck art graphics, colorful illustrated designs, skate culture street style' },
      { label: 'Band merch print', prompt: 'Add oversized band t-shirt graphic with skeleton or grim reaper art, bootleg concert tee design' },
      { label: 'Spray stencil art', prompt: 'Apply Banksy-style stencil spray paint art, single-color street art image sprayed over the fabric' },
      { label: 'Rave flyer print', prompt: 'Cover with garish 90s rave flyer graphics, neon smiley faces and psychedelic type on dark fabric' },
      { label: 'Bleach acid wash', prompt: 'Apply irregular bleach acid wash treatment, pale blotchy faded patches on dark denim, 80s denim aesthetic' },
      { label: 'Barbed wire wrap', prompt: 'Wind barbed wire around the sleeves and collar, sharp metal barbs and twisted wire, hostile aesthetic' },
    ],
  },
  {
    label: '🌈 Patterns',
    options: [
      { label: 'Tie-dye spiral', prompt: 'Transform into vibrant tie-dye with swirling spirals of purple, blue, pink, and yellow, psychedelic pattern' },
      { label: 'Hawaiian floral', prompt: 'Transform into Hawaiian shirt pattern with tropical hibiscus flowers, palm leaves, bright island colors' },
      { label: 'Optical illusion', prompt: 'Apply M.C. Escher style optical illusion geometric pattern, impossible shapes in black and white' },
      { label: 'Mandala geometric', prompt: 'Apply intricate mandala geometric pattern with concentric circles and repeating symmetrical designs' },
      { label: 'Racing stripes', prompt: 'Add bold racing stripes running vertically, white stripes on dark fabric, motorsport style' },
      { label: 'Checkerboard', prompt: 'Apply bold black and white checkerboard pattern, alternating square tiles, ska punk racing flag style' },
      { label: 'Houndstooth', prompt: 'Apply black and white houndstooth check pattern, interlocking broken checks, classic British fashion textile' },
      { label: 'Paisley swirls', prompt: 'Apply ornate paisley swirl pattern in rich jewel tones, curved teardrop shapes with intricate interior detail' },
      { label: 'Polka dots large', prompt: 'Apply bold large polka dots in a contrasting color, evenly spaced round circles, retro 60s mod fashion' },
      { label: 'Horizontal stripes', prompt: 'Apply nautical horizontal stripes in navy and white, classic Breton sailor stripe pattern, marine style' },
      { label: 'Plaid flannel', prompt: 'Apply thick flannel plaid grid pattern in red and black, lumberjack flannel shirt textile look' },
    ],
  },
  {
    label: '⚡ Sci-Fi & Tech',
    options: [
      { label: 'Tron circuit lines', prompt: 'Add glowing neon circuit lines tracing across the fabric, bright cyan light strips, futuristic digital grid' },
      { label: 'Holographic shimmer', prompt: 'Apply iridescent holographic finish shifting between rainbow colors, opalescent shimmering surface' },
      { label: 'Carbon fiber', prompt: 'Transform into carbon fiber weave pattern, dark grey interlocking diagonal fibers, lightweight tech material' },
      { label: 'LED strips', prompt: 'Add embedded LED light strips along seams and edges, glowing colored lights, wearable tech fashion' },
      { label: 'Matrix code', prompt: 'Cover with falling green Matrix digital rain code, cascading Japanese characters on dark background' },
      { label: 'Wireframe mesh', prompt: 'Transform into 3D wireframe mesh, geometric polygon outlines in glowing blue on dark, virtual reality look' },
      { label: 'Nano-suit scales', prompt: 'Cover with interlocking nano-material scales that flex and shift, iridescent metamaterial surface, Crysis style' },
      { label: 'Data stream print', prompt: 'Print cascading data streams and network packet visualizations across the fabric, information superhighway design' },
      { label: 'Hard-light panels', prompt: 'Replace fabric with glowing hard-light energy panels, opaque laser construct segments, sci-fi energy shield suit' },
      { label: 'Exo-armor overlay', prompt: 'Attach lightweight exo-armor overlays at shoulders elbows and forearms, sleek civilian augmentation suit' },
    ],
  },
  {
    label: '⚔️ Medieval & Fantasy',
    options: [
      { label: 'Chainmail armor', prompt: 'Replace with medieval chainmail armor, interlocking metal rings, silver steel links, knight warrior look' },
      { label: 'Plate armor', prompt: 'Transform into polished plate armor segments, heavy steel plates with rivets, full knight armor' },
      { label: 'Dragon scales', prompt: 'Cover with overlapping dragon scales, iridescent green-gold reptilian armor, fantasy creature texture' },
      { label: 'Rune inscriptions', prompt: 'Carve glowing ancient rune symbols and mystical inscriptions into the surface, magical Nordic lettering' },
      { label: 'Royal crest', prompt: 'Add an ornate royal coat of arms crest embroidered on the chest, heraldic shield with lion motif' },
      { label: 'Elven leaf embroidery', prompt: 'Add intricate elvish leaf and vine embroidery in silver thread, delicate nature-inspired fantasy stitching' },
      { label: 'Tattered battle standard', prompt: 'Drape a torn war-battle standard banner across the clothing, faded heraldic colors, frayed edges from battle' },
      { label: 'Paladin holy armor', prompt: 'Add gleaming paladin holy armor trim with divine sun motif engravings, sacred warrior embellishments' },
      { label: 'Mage robes layers', prompt: 'Add layered arcane mage robe panels in deep blue with silver star constellation embroidery, spellcaster garb' },
      { label: 'Bandits wrap', prompt: 'Wrap the torso in rough brown bandage cloth with leather cord bindings, outlaw desert wanderer look' },
      { label: 'Phoenix crest emblem', prompt: 'Embroider a large phoenix rising in orange-red gold thread crest on the chest, rebirth and fire emblem' },
    ],
  },
  {
    label: '🍕 Weird & Fun',
    options: [
      { label: 'Pizza pattern', prompt: 'Cover with pepperoni pizza pattern, melted cheese and tomato sauce, repeating pizza slice print' },
      { label: 'Blood splatter', prompt: 'Add dark red blood splatter and drip stains across the fabric, horror movie gory look' },
      { label: 'Candy sprinkles', prompt: 'Cover with colorful candy sprinkles and jimmies, rainbow sugar confetti on frosting-like surface' },
      { label: 'Bacon weave', prompt: 'Transform into woven bacon strips pattern, crispy cooked bacon lattice weave, meat fabric' },
      { label: 'Duct tape wrapped', prompt: 'Wrap in strips of grey duct tape, overlapping pieces of adhesive tape, makeshift repair look' },
      { label: 'Bubblewrap texture', prompt: 'Transform into clear bubblewrap with visible air bubbles, transparent popping packaging material texture' },
      { label: 'Tin foil wrapped', prompt: 'Wrap in crinkled aluminium tin foil sheets, shiny creased metal foil conspiracy theorist fashion' },
      { label: 'Band-aid covered', prompt: 'Plaster with dozens of overlapping beige band-aids applied in all directions, wound care fashion statement' },
      { label: 'Money bills pinned', prompt: 'Pin paper money bills all over the clothing with safety pins, literal money suit, cash fashion' },
      { label: 'Googly eyes stuck on', prompt: 'Stick hundreds of plastic googly eyes all over the clothing, plastic wiggly eyes in every size' },
      { label: 'Lego bricks attached', prompt: 'Attach colorful Lego bricks all over the clothing, snapped-on plastic building blocks, construction toy fashion' },
    ],
  },
  {
    label: '⚡ Energy & Power',
    options: [
      { label: 'Energy aura crackling', prompt: 'Add visible crackling energy aura around the clothing, electric blue power field sparking outward' },
      { label: 'Power-up glow', prompt: 'Add intense golden power-up glow radiating from the clothing, super saiyan energy emanation' },
      { label: 'Divine golden light', prompt: 'Add divine golden holy light rays emanating from the clothing, heavenly sacred glow effect' },
      { label: 'Ki blast sparks', prompt: 'Add bright white ki energy sparks and particles swirling around the clothing, anime power effect' },
      { label: 'Magical particles', prompt: 'Add floating magical sparkle particles and fairy dust swirling around the clothing, enchanted shimmer' },
      { label: 'Lightning surge', prompt: 'Add blue-white lightning bolts crackling and surging around the clothing, electrical power overload' },
      { label: 'Dark void aura', prompt: 'Surround clothing with a consuming dark void aura, black hole gravity distorting space at the edges' },
      { label: 'Phoenix fire rebirth', prompt: 'Engulf clothing in phoenix rebirth fire, rising flame bird silhouette emerging from the burning fabric' },
      { label: 'Plasma ball tendrils', prompt: 'Add plasma ball tendrils of purple electricity arcing outward from the clothing, plasma globe effect' },
      { label: 'Demonic corruption', prompt: 'Corrupt clothing with dark demonic energy, black veins spreading outward, hellfire licking at the edges' },
      { label: 'Chi energy flow', prompt: 'Channel visible chi energy flow through clothing, orange-red life force coursing through defined meridian lines' },
    ],
  },
  {
    label: '👴 Worn & Aged',
    options: [
      { label: 'Sun-bleached faded', prompt: 'Make colors faded and sun-bleached, washed out from years of sunlight exposure, vintage worn look' },
      { label: 'Moth-eaten holes', prompt: 'Add small moth-eaten holes scattered through the fabric, aged deteriorating cloth, old wardrobe look' },
      { label: 'Blood stained', prompt: 'Add old dried blood stain marks on the fabric, dark brown-red aged bloodstains, battle veteran look' },
      { label: 'Patched & repaired', prompt: 'Add visible fabric patches sewn over holes, mismatched repair patches with visible stitching' },
      { label: 'Dust covered', prompt: 'Cover with fine layer of grey dust and cobwebs, abandoned and neglected, found in an attic look' },
      { label: 'Sweat stained', prompt: 'Add visible sweat stains and salt marks, yellowed discoloration, heavily worn workout look' },
      { label: 'Paint splattered work', prompt: 'Cover in dried paint splatters from years of work, multi-color drips and smears, house painter clothing' },
      { label: 'Oil grease smeared', prompt: 'Smear with dark engine grease and motor oil stains, mechanic workshop grime on the fabric' },
      { label: 'Mud caked', prompt: 'Cake with dried grey-brown mud, thick dried dirt clods clinging to the fabric, post-trench warfare' },
      { label: 'Frayed cuffs & collar', prompt: 'Fray the collar and cuffs with pulled threads hanging loose, worn thin from too many washings' },
    ],
  },
];

// --- Head-Only Enhance Families ---

const HEAD_ENHANCE: AIStyleFamily[] = [
  {
    label: '⚙️ Steampunk',
    options: [
      { label: 'Brass gears & cogs', prompt: 'Add brass clockwork gears and rotating cogs attached to the surface, Victorian mechanical aesthetic' },
      { label: 'Copper pipe network', prompt: 'Add small copper pipes and tube fittings running across the surface, industrial plumbing steampunk style' },
      { label: 'Steam vents', prompt: 'Add small steam vent openings releasing wisps of white steam, pressure release valves' },
      { label: 'Tesla coil sparks', prompt: 'Add miniature Tesla coil apparatus with visible purple electrical arcs and sparks, mad scientist style' },
      { label: 'Pressure gauge dials', prompt: 'Add round brass pressure gauge dials with needles and numbered faces mounted on the surface' },
      { label: 'Leather & rivet binding', prompt: 'Wrap with brown leather straps held by brass rivets and buckles, steampunk adventurer aesthetic' },
      { label: 'Pocket watch inlaid', prompt: 'Inlay an ornate brass pocket watch face into the surface, roman numeral clock face, ticking timepiece' },
      { label: 'Boiler pressure rivets', prompt: 'Stud with large boiler-grade rivets in rows, thick iron dome rivets holding metal plates together' },
      { label: 'Aetheric crystal power', prompt: 'Add a glowing blue aether crystal power source mounted prominently, steampunk energy conduit' },
      { label: 'Monocle attachment', prompt: 'Mount a brass monocle eyepiece with articulating arm, magnifying lens on mechanical pivot arm' },
      { label: 'Welding goggle brackets', prompt: 'Add dark smoked welding goggle lenses in round brass frames, flip-up tinted protective eye shields' },
      { label: 'Wind-up key back', prompt: 'Insert a large winding key protruding from the back, clockwork automaton wind-up toy mechanism' },
    ],
  },
  {
    label: '🔮 Magical',
    options: [
      { label: 'Glowing runes', prompt: 'Add glowing magical rune symbols carved into the surface, bright blue-white mystical Norse letters' },
      { label: 'Crystal embedded', prompt: 'Embed large colorful crystals and gems growing from the surface, amethyst quartz formations' },
      { label: 'Starfield pattern', prompt: 'Apply deep space starfield pattern across the surface, tiny stars and nebula colors, cosmic night sky' },
      { label: 'Ancient spell pages', prompt: 'Wrap with ancient parchment spell pages covered in mystical handwritten text and arcane diagrams' },
      { label: 'Phoenix feather crown', prompt: 'Add majestic phoenix feathers in orange-red-gold rising from the top, magical firebird plumage' },
      { label: 'Shadow tendrils', prompt: 'Add dark shadow tendrils and black smoke wisps curling around the surface, dark magic aura' },
      { label: 'Astral projection glow', prompt: 'Add astral projection aura glowing in silver-blue, out-of-body spiritual light separating from physical form' },
      { label: 'Curse mark seal', prompt: 'Burn a glowing curse mark seal onto the surface, dark sigil brand with pulsing red-black malevolent glow' },
      { label: 'Fairy dust cloud', prompt: 'Surround with sparkling fairy dust cloud, tiny glittering motes in pink and gold drifting outward' },
      { label: 'Tarot card imagery', prompt: 'Overlay tarot card symbolic imagery, The Moon or Death card arcane symbols etched onto the surface' },
      { label: 'Soul flame crown', prompt: 'Top with a crown of soul flames in deep blue and white, ghostfire halo of unquenchable spirit energy' },
      { label: 'Enchanted mirror', prompt: 'Embed a small enchanted scrying mirror showing another realm, deep black mirror with ghostly visions' },
    ],
  },
  {
    label: '🧢 Patches & Pins',
    options: [
      { label: 'Embroidered logo', prompt: 'Add a colorful embroidered logo patch stitched onto the front, custom embroidery with thick thread' },
      { label: 'Iron-on patches', prompt: 'Add multiple iron-on fabric patches with various designs scattered on the surface, DIY custom look' },
      { label: 'Enamel pin collection', prompt: 'Add small colorful enamel pins stuck into the surface, collection of cute cartoon badge pins' },
      { label: 'Sewn-on badges', prompt: 'Add circular sewn-on merit badges and scout patches in a row, achievement badge collection' },
      { label: 'Screen-printed design', prompt: 'Add bold screen-printed graphic design on the front, single color ink print, skate brand style' },
      { label: 'Bleach-dye splash', prompt: 'Add bleach splash dye effect creating lighter discolored patches, acid wash DIY streetwear look' },
      { label: 'Vintage team patch', prompt: 'Add a vintage sports team embroidered patch, old-school athletic club branding on worn felt backing' },
      { label: 'National flag patch', prompt: 'Sew a small country flag patch onto the brim, woven nation flag textile badge, traveler collection' },
      { label: 'Smiley face pin', prompt: 'Pin a classic yellow smiley face button badge, 90s rave icon happy face enamel pin' },
      { label: 'Woven name tape', prompt: 'Stitch a woven name tape with custom text across the front, military name bar in block letters' },
      { label: 'Varsity letter felt', prompt: 'Add a large varsity letter cut from thick felt, school athletic letter with chenille borders' },
      { label: 'Destination sticker', prompt: 'Slap travel destination stickers across the surface, vintage luggage label style city stickers' },
    ],
  },
  {
    label: '🤠 Weathered & Adventure',
    options: [
      { label: 'Sun-bleached & faded', prompt: 'Make colors faded and sun-bleached from years outdoors, washed out from desert sun exposure' },
      { label: 'Rain-soaked wet', prompt: 'Make look freshly rain-soaked, darkened wet fabric with visible water droplets and dripping moisture' },
      { label: 'Dust & sand coated', prompt: 'Cover with fine desert sand and trail dust, dirty and dusty from long wilderness journey' },
      { label: 'Bullet hole through brim', prompt: 'Add a single bullet hole punched clean through with singed edges, close call gunshot damage' },
      { label: 'Feather & bone decoration', prompt: 'Add feathers and small animal bones tied on with leather cord, wilderness survival decoration' },
      { label: 'Sweat-stained band', prompt: 'Add dark sweat stain ring around the band, salt crystallization marks, well-worn working hat' },
      { label: 'Campfire smoke', prompt: 'Darken and season with campfire smoke residue, black carbon deposits from nights around open flames' },
      { label: 'Trail mud splattered', prompt: 'Spatter with hiking trail mud, brown clay mud dots and streaks from mountain trail running' },
      { label: 'Paracord lashed', prompt: 'Lash paracord cordage around the exterior, survival paracord wrapping in olive drab and black' },
      { label: 'Expedition stamp', prompt: 'Brand with expedition stamping marks, date and location rubber stamps from various explorations' },
      { label: 'Repair stitches crude', prompt: 'Add crude field-repair stitches closing a tear, rough uneven hand-stitching with thick waxed thread' },
      { label: 'Jungle rot', prompt: 'Rot with tropical jungle mildew, green-black mold patches and moisture damage from humid rainforest' },
    ],
  },
  {
    label: '🍬 Food & Candy',
    options: [
      { label: 'Chocolate coated', prompt: 'Dip in rich dark chocolate coating, smooth melted chocolate shell with drip marks, candy confection' },
      { label: 'Candy cane stripes', prompt: 'Apply red and white candy cane spiral stripe pattern, peppermint Christmas candy look' },
      { label: 'Gummy bear texture', prompt: 'Transform into translucent gummy bear candy material, shiny gel-like jiggly surface, candy colors' },
      { label: 'Donut glaze & sprinkles', prompt: 'Cover with pink donut glaze icing dripping down with colorful rainbow sprinkles on top' },
      { label: 'Caramel dripping', prompt: 'Cover with warm golden caramel sauce dripping and pooling, sticky sweet toffee coating' },
      { label: 'Frosting & fondant', prompt: 'Cover with smooth cake frosting and fondant in pastel colors, birthday cake decoration style' },
      { label: 'Cotton candy fluff', prompt: 'Encase in spun cotton candy fluff, pastel pink and blue sugary cloud wisps clinging to the surface' },
      { label: 'Rock candy crystals', prompt: 'Grow rock candy sugar crystals all over, angular translucent sugar crystal clusters in vivid colors' },
      { label: 'Gingerbread texture', prompt: 'Transform into baked gingerbread, warm brown spiced cookie surface with crackling sugar glaze' },
      { label: 'Waffle cone texture', prompt: 'Transform surface into waffle cone grid texture, crispy golden-brown diagonal waffle pattern' },
      { label: 'Gummy worm pile', prompt: 'Pile colorful gummy worms draped across the surface, translucent striped worm candies in a heap' },
      { label: 'Lollipop swirl', prompt: 'Apply giant lollipop spiral pattern, radiating swirl of bright candy colors from center outward' },
    ],
  },
  {
    label: '🧊 Material Swap',
    options: [
      { label: 'Carved wood', prompt: 'Transform into hand-carved wood with visible grain pattern and chisel marks, wooden sculpture' },
      { label: 'Marble stone', prompt: 'Transform into polished marble with white and grey veined stone pattern, classical sculpture material' },
      { label: 'Glass transparent', prompt: 'Transform into clear transparent glass, see-through crystalline material, delicate blown glass' },
      { label: 'Paper origami', prompt: 'Transform into folded paper origami, visible paper creases and geometric folds, Japanese paper art' },
      { label: 'Bone & ivory', prompt: 'Transform into carved bone and ivory material, aged yellowed skeletal surface, tribal artifact' },
      { label: 'Clay ceramic', prompt: 'Transform into fired clay ceramic with visible pottery glazing, handmade terracotta crafted look' },
      { label: 'Wicker basket weave', prompt: 'Transform into woven wicker basket material, interlaced natural reed strips, handcrafted botanical weave' },
      { label: 'Sponge foam', prompt: 'Transform into soft yellow sponge foam material, porous open-cell texture, squeezable foam block' },
      { label: 'Concrete cast', prompt: 'Transform into rough poured concrete, grey mineral aggregate surface with form-board marks and air bubbles' },
      { label: 'Rubber vulcanized', prompt: 'Transform into thick vulcanized rubber, dark charcoal matte surface, sturdy industrial rubber compound' },
      { label: 'Ice block frozen', prompt: 'Encase in a solid ice block, suspended in clear frozen ice with air bubble inclusions and frost cracking' },
      { label: 'Felted wool', prompt: 'Transform into dense matted wool felt, short fibre surface in natural undyed grey-white, craft felt material' },
    ],
  },
];

// --- Create New Families ---

const CLOTHES_CREATE: AIStyleFamily[] = [
  {
    label: '⚔️ Armor & Warriors',
    options: [
      { label: 'Knight plate armor', prompt: 'Full medieval knight plate armor suit with chest plate, pauldrons, and gauntlets, polished steel' },
      { label: 'Samurai yoroi armor', prompt: 'Traditional Japanese samurai yoroi armor with layered lacquered plates and silk cord lacing' },
      { label: 'Gladiator chest plate', prompt: 'Roman gladiator chest plate with leather straps, bronze chest guard, arena fighter gear' },
      { label: 'Viking chain armor', prompt: 'Viking chainmail armor tunic over leather underlayer, Norse warrior battle gear with fur shoulders' },
      { label: 'Spartan battle gear', prompt: 'Spartan warrior crimson cape and bronze chest plate, leather war skirt, 300 battle outfit' },
      { label: 'Dark lord shadow armor', prompt: 'Evil dark lord black spiked plate armor, dark enchanted metal with red glowing runes, villain armor' },
      { label: 'Mongol lamellar armor', prompt: 'Mongolian warrior lamellar armor, rows of small lacquered leather plates laced together, steppe warrior' },
      { label: 'Aztec warrior suit', prompt: 'Aztec jaguar warrior suit, spotted jaguar skin outfit with feathered headdress, Mesoamerican warrior' },
      { label: 'Roman legionnaire lorica', prompt: 'Roman legion lorica segmentata segmented iron plate armor, articulated shoulder and torso protection' },
      { label: 'Zulu warrior regalia', prompt: 'Zulu warrior battle regalia with cowhide shield, beaded chest piece, and leopard skin ceremonial garb' },
      { label: 'Persian immortal armor', prompt: 'Persian immortal warrior armor with ornate tunic over scale mail, golden mask and elaborate decoration' },
      { label: 'Celtic battle harness', prompt: 'Celtic tribal battle harness with torque neck ring, woad-painted chest, and tartan war cloak' },
    ],
  },
  {
    label: '👔 Formal & Elegant',
    options: [
      { label: 'Royal tuxedo with tails', prompt: 'Formal black tuxedo with long tails, white dress shirt, black bow tie, elegant evening wear' },
      { label: 'Victorian frock coat', prompt: 'Victorian era long frock coat in dark grey, high collar, ornate buttons, gentleman period clothing' },
      { label: 'White dinner jacket', prompt: 'Classic white dinner jacket with black satin lapels, formal resort evening wear, James Bond style' },
      { label: 'Velvet smoking jacket', prompt: 'Rich burgundy velvet smoking jacket with silk shawl collar, quilted satin lining, luxury lounge wear' },
      { label: 'Military dress uniform', prompt: 'Formal military dress uniform with gold braiding, epaulettes, medal ribbons, and polished buttons' },
      { label: 'Maharaja sherwani', prompt: 'Ornate Indian maharaja sherwani coat in gold brocade, intricate embroidery, royal Indian formal wear' },
      { label: 'Opera cape & white tie', prompt: 'Grand opera cape in black silk with white satin lining, white tie and tails, premiere night formal dress' },
      { label: 'Double-breasted suit', prompt: 'Sharp double-breasted pinstripe suit in navy blue with peak lapels, power suit, 1940s gangster elegance' },
      { label: 'Nehru collar jacket', prompt: 'Slim Nehru collar jacket in black with no lapels, 1960s mod formal, Bond villain elegance' },
      { label: 'Naval dress uniform', prompt: 'Royal naval officers dress uniform with gold epaulettes, admiral braiding, and row of campaign medals' },
      { label: 'Haute couture avant-garde', prompt: 'Impossibly structured haute couture avant-garde gown with geometric sculptural panels, Paris fashion week runway' },
    ],
  },
  {
    label: '🧪 Sci-Fi & Future',
    options: [
      { label: 'Space marine power suit', prompt: 'Heavy space marine power armor suit, thick armored plates, glowing power cells, futuristic soldier' },
      { label: 'Cyberpunk neon jacket', prompt: 'Cyberpunk leather jacket with glowing neon trim lines, high collar, tech augmentation ports' },
      { label: 'Holographic bodysuit', prompt: 'Skin-tight holographic bodysuit shifting between rainbow colors, futuristic iridescent material' },
      { label: 'Robot exoskeleton', prompt: 'Mechanical robot exoskeleton frame over the body, hydraulic joints, exposed servos and wiring' },
      { label: 'Alien symbiote suit', prompt: 'Living alien symbiote suit bonded to the body, dark organic material with tendrils, Venom-like' },
      { label: 'Tron light suit', prompt: 'Black bodysuit with bright glowing blue circuit lines, Tron legacy digital world light cycle suit' },
      { label: 'Zero-G flight suit', prompt: 'White NASA zero-gravity flight suit with mission patches, pressurized joints, ISS astronaut attire' },
      { label: 'Biomech integration suit', prompt: 'Biomechanical integration suit where organic tissue and machine components have merged, HR Giger aesthetic' },
      { label: 'Hazmat decontamination', prompt: 'Full yellow hazmat decontamination suit with respirator hood, chemical resistant material, biohazard response gear' },
      { label: 'Stealth meta-material cloak', prompt: 'Meta-material stealth cloak coat that bends light around the wearer, near-invisible light-bending fabric' },
      { label: 'Cryogenic stasis suit', prompt: 'Cryogenic stasis suit with internal heating elements, frost-white insulated material, long-sleep travel wear' },
    ],
  },
  {
    label: '🧙 Fantasy & Magical',
    options: [
      { label: 'Wizard grand robe', prompt: 'Flowing wizard grand robe in deep purple with gold stars and moons, long sleeves, pointed collar' },
      { label: 'Druid leaf cloak', prompt: 'Forest druid cloak made of interwoven green leaves and vines, natural woodland camouflage' },
      { label: 'Necromancer dark robes', prompt: 'Dark necromancer robes in black and deep purple, tattered edges, skull clasps, death magic aura' },
      { label: 'Elven silver tunic', prompt: 'Elegant elven tunic in silver-grey with intricate leaf embroidery, lightweight enchanted elven cloth' },
      { label: 'Alchemist coat', prompt: 'Alchemist leather coat with potion vials in belt loops, stained from experiments, mystic symbols' },
      { label: 'Enchanted crystal armor', prompt: 'Armor made of glowing magical crystals, translucent gem-like plates in blue and purple, fantasy' },
      { label: 'Bard travelling cloak', prompt: 'Bard travelling cloak in rich burgundy with lute-shaped clasp, colorful motley patches, jester patchwork' },
      { label: 'Fae thorn armor', prompt: 'Faerie thorn armor grown from living branches, green wood plates with flowering vines, nature fae warrior' },
      { label: 'Astromancer vestments', prompt: 'Astromancer vestments embroidered with star charts and constellation maps, midnight blue silk, sky magic' },
      { label: 'Oracle sheer robes', prompt: 'Sheer oracle robes in white and gold, translucent layered fabric, prophetic visions embroidered at hem' },
      { label: 'Goblin patchwork gear', prompt: 'Goblin scavenged patchwork gear, mismatched salvaged parts stitched crudely, found-junk tinkerer outfit' },
      { label: 'Storm caller vestment', prompt: 'Storm caller vestment crackling with static, lightning-struck char marks, electrified shaman weather magic' },
    ],
  },
  {
    label: '🎭 Costumes & Characters',
    options: [
      { label: 'Superhero spandex suit', prompt: 'Colorful superhero spandex bodysuit with bold chest emblem, cape, bright primary colors' },
      { label: 'Ninja stealth outfit', prompt: 'Black ninja stealth outfit with wrapped cloth, utility belt, face covering, shadow warrior' },
      { label: 'Pirate captain coat', prompt: 'Pirate captain long coat in dark red with gold trim, brass buttons, weathered sea-worn look' },
      { label: 'Cowboy duster jacket', prompt: 'Long brown leather cowboy duster coat, worn and dusty, western frontier outlaw style' },
      { label: 'Detective trench coat', prompt: 'Classic noir detective tan trench coat with belt, popped collar, mysterious investigator look' },
      { label: 'Jungle explorer vest', prompt: 'Khaki jungle explorer vest with many pockets, compass, and binoculars, adventure gear' },
      { label: 'Vampire hunter rig', prompt: 'Vampire hunter leather rig with crossbow bolts in bandoliers, garlic bulb pouches, Van Helsing gear' },
      { label: 'Steampunk sky pirate', prompt: 'Sky pirate leather coat with goggles, compass, and map scroll holder, airship buccaneer adventurer' },
      { label: 'Bounty hunter vest', prompt: 'Mandalorian-style bounty hunter beskar vest, scratched battle-worn bounty tracking gear, space western' },
      { label: 'Viking shield maiden', prompt: 'Viking shield maiden linen dress with leather armor pieces, arm rings, Norse female warrior outfit' },
      { label: 'Apocalypse scavenger', prompt: 'Post-apocalypse scavenger outfit, layered salvaged clothing, makeshift armor plates, wastelander survivor' },
      { label: 'Circus ringmaster', prompt: 'Circus ringmaster top hat and tailcoat in red and black, gold trim, handlebar moustache implied formal wear' },
    ],
  },
  {
    label: '👷 Uniforms & Work',
    options: [
      { label: 'Chef double-breasted coat', prompt: 'White chef double-breasted coat with cloth buttons, kitchen uniform, professional cook attire' },
      { label: 'Doctor lab coat', prompt: 'White doctor lab coat with stethoscope around neck, hospital ID badge, medical professional' },
      { label: 'Pilot flight suit', prompt: 'Military pilot flight suit in olive green with patches, survival vest, aviator jumpsuit' },
      { label: 'Racing driver jumpsuit', prompt: 'Racing driver fireproof jumpsuit covered in sponsor logos, colorful motorsport uniform' },
      { label: 'Construction hi-vis vest', prompt: 'Orange high-visibility construction worker vest with reflective strips over work clothes' },
      { label: 'Prison jumpsuit', prompt: 'Orange prison jumpsuit with stenciled numbers on chest, institutional correctional facility uniform' },
      { label: 'Firefighter turnout gear', prompt: 'Firefighter turnout coat in yellow with reflective SCBA stripes, heavy protective fire proximity gear' },
      { label: 'Astronaut EVA suit', prompt: 'White NASA EVA extravehicular activity suit, spherical helmet ring, life support backpack connections' },
      { label: 'Train conductor', prompt: 'Victorian train conductor uniform, navy double-breasted coat, conductor cap, gold pocket watch on chain' },
      { label: 'Sushi chef uniform', prompt: 'Japanese sushi chef uniform with white hachimaki headband and white apron, itamae master outfit' },
      { label: 'Circus clown suit', prompt: 'Oversized polka dot circus clown suit with ruffled collar, enormous buttons, comedy performance costume' },
      { label: 'Park ranger uniform', prompt: 'US National Park Service ranger uniform, olive grey shirt with badge, flat campaign hat, forest service pride' },
    ],
  },
  {
    label: '🏋️ Sports & Athletic',
    options: [
      { label: 'Boxing robe & gloves', prompt: 'Satin boxing robe with hood and boxing gloves, champion fighter walk-out outfit' },
      { label: 'Basketball jersey', prompt: 'Sleeveless basketball jersey with number and team name, athletic mesh fabric, NBA style' },
      { label: 'Football pads & jersey', prompt: 'American football jersey with shoulder pads underneath, team colors, NFL game day gear' },
      { label: 'Martial arts gi', prompt: 'White martial arts gi karate uniform with black belt, traditional dojo training outfit' },
      { label: 'Wrestling singlet', prompt: 'Tight wrestling singlet one-piece in bold colors, athletic competition bodysuit, Olympic style' },
      { label: 'Hockey jersey & pads', prompt: 'Ice hockey jersey with shoulder and elbow pads, team logo on chest, NHL game uniform' },
      { label: 'Tour de France jersey', prompt: 'Tour de France yellow leader cycling jersey, maillot jaune with sponsor logos, road cycling champion' },
      { label: 'Tennis whites outfit', prompt: 'Classic Wimbledon tennis whites, crisp white polo shirt and shorts, all-white court dress code' },
      { label: 'Formula 1 firesuit', prompt: 'Formula 1 racing driver firesuit covered in sponsor logos, fireproof Nomex material, pit lane fashion' },
      { label: 'Rock climbing harness', prompt: 'Rock climbing harness with belay loops, chalk bag on hip, carabiner clips, vertical sports gear' },
      { label: 'Fencing jacket', prompt: 'White fencing jacket with lame scoring jacket overlay, chest guard, right-handed fencer competition attire' },
    ],
  },
  {
    label: '🌍 Cultural & Traditional',
    options: [
      { label: 'Japanese kimono', prompt: 'Traditional Japanese kimono robe with obi belt, ornate floral patterns, silk formal wear' },
      { label: 'Scottish kilt & jacket', prompt: 'Scottish Highland kilt in tartan plaid with formal Argyll jacket and sporran, Celtic dress' },
      { label: 'Hawaiian lei & shirt', prompt: 'Bright Hawaiian aloha shirt with tropical prints and flower lei garland around the neck' },
      { label: 'Mexican poncho', prompt: 'Colorful Mexican poncho with striped pattern and fringe edges, traditional serape blanket wear' },
      { label: 'Indian kurta', prompt: 'Ornate Indian kurta tunic with embroidered neckline, lightweight cotton formal wear, festive colors' },
      { label: 'Egyptian pharaoh tunic', prompt: 'Ancient Egyptian pharaoh royal tunic with gold collar necklace, white linen with gold trim' },
      { label: 'Chinese hanfu robe', prompt: 'Traditional Chinese hanfu cross-collar robe in flowing silk with wide sleeves, dynasty era formal wear' },
      { label: 'Korean hanbok', prompt: 'Traditional Korean hanbok with wide jeogori jacket and full chima skirt in vibrant complementary colors' },
      { label: 'Dashiki shirt', prompt: 'West African dashiki shirt in bold kente-inspired geometric pattern, vibrant orange and yellow colors' },
      { label: 'Maori warrior cloak', prompt: 'Maori warrior feather cloak with taniko woven border, koru spiral design, New Zealand indigenous garb' },
      { label: 'Greek chiton', prompt: 'Ancient Greek chiton draped garment in white linen with colored border, fibula pin at shoulder, toga style' },
      { label: 'Moroccan djellaba', prompt: 'Moroccan djellaba hooded robe in cream with colorful embroidery at neckline, North African lounge wear' },
    ],
  },
  {
    label: '💀 Dark & Horror',
    options: [
      { label: 'Zombie torn rags', prompt: 'Torn and shredded zombie clothes with dirt and blood stains, decaying undead horror outfit' },
      { label: 'Vampire cape & vest', prompt: 'Gothic vampire outfit with high-collar black cape and red lining, Victorian vest, Dracula style' },
      { label: 'Mummy wrappings', prompt: 'Ancient Egyptian mummy wrappings, dirty aged linen bandages wrapped around the body, undead' },
      { label: 'Skeleton bone armor', prompt: 'Armor made from bones and skulls, skeletal rib cage chest piece, necromantic bone construction' },
      { label: 'Werewolf torn shirt', prompt: 'Shredded torn shirt from werewolf transformation, ripped fabric revealing fur, mid-transform horror' },
      { label: 'Ghostly translucent robes', prompt: 'Semi-transparent ghostly flowing robes, ethereal see-through spectral fabric, haunting spirit' },
      { label: 'Scarecrow straw stuffed', prompt: 'Scarecrow costume with straw bursting from sleeves and collar, burlap face sack, cornfield horror' },
      { label: 'Undead general uniform', prompt: 'Undead general rotting military uniform with exposed bone at collar, skull buttons, death commander' },
      { label: 'Cult ritual robe', prompt: 'Crimson cult ritual robe with hood pulled forward, arcane symbol on chest, dark congregation ceremony wear' },
      { label: 'Asylum straitjacket', prompt: 'White leather asylum straitjacket with buckle restraint straps, buckled closed, psychiatric horror look' },
      { label: 'Lovecraftian robe', prompt: 'Lovecraftian cultist robe in deep sea green with elder sign embroidered, non-Euclidean hem patterns' },
    ],
  },
  {
    label: '🤪 Absurd & Meme',
    options: [
      { label: 'Banana costume', prompt: 'Full banana fruit costume, yellow banana bodysuit with brown top, comedy fruit outfit' },
      { label: 'Inflatable T-Rex suit', prompt: 'Inflatable T-Rex dinosaur costume, puffy oversized green dino suit, viral meme outfit' },
      { label: 'Cardboard box robot', prompt: 'Cardboard box robot costume with drawn-on buttons and dials, homemade craft project outfit' },
      { label: 'Bubble wrap bodysuit', prompt: 'Full bodysuit made of clear bubble wrap, see-through popping packaging material, absurd fashion' },
      { label: 'Trash bag couture', prompt: 'High fashion outfit made entirely from shiny black trash bags, garbage bag runway fashion' },
      { label: 'Barrel & suspenders', prompt: 'Classic wooden barrel with suspender straps, lost-everything cartoon poverty barrel outfit' },
      { label: 'Hot dog costume', prompt: 'Full hot dog bun costume, yellow mustard stripes on a giant wiener bun, America in food form' },
      { label: 'Newspaper toga', prompt: 'Toga made entirely of crumpled newspaper pages, ancient Rome meets broke college student energy' },
      { label: 'Pool noodle armor', prompt: 'Makeshift armor constructed from brightly colored foam pool noodles taped together, backyard warrior' },
      { label: 'Duct tape couture', prompt: 'Entire outfit constructed from overlapping strips of duct tape, prom dress made from grey adhesive tape' },
      { label: 'Toilet paper mummy', prompt: 'Wrapped head to toe in toilet paper like a mummy, Halloween cheapskate costume, pandemic flashback' },
    ],
  },
];

const HEAD_CREATE: AIStyleFamily[] = [
  {
    label: '⚔️ Helmets & Armor',
    options: [
      { label: 'Knight great helm', prompt: 'Medieval knight great helm bucket helmet with narrow eye slit and cross visor, full steel' },
      { label: 'Spartan corinthian helmet', prompt: 'Bronze Spartan corinthian helmet with tall red mohawk crest plume, Greek warrior' },
      { label: 'Samurai kabuto', prompt: 'Japanese samurai kabuto helmet with crescent moon crest, face guard mask, lacquered metal' },
      { label: 'Space marine helmet', prompt: 'Futuristic space marine full enclosed helmet, thick armored plating, glowing visor slit' },
      { label: 'Gladiator helm', prompt: 'Roman gladiator visored helmet with metal grill face guard and feather crest, arena fighter' },
      { label: 'Barbarian skull helm', prompt: 'Savage barbarian helmet made from a large animal skull with horns, bone and leather' },
      { label: 'Dwarven mining helm', prompt: 'Dwarven mining helmet with front lantern, protective ear guards, riveted iron dome, underground dwarf headgear' },
      { label: 'Norman nasal helm', prompt: 'Norman conical nasal guard helmet with metal strip protecting the nose, 1066 Hastings era warrior' },
      { label: 'WW1 doughboy helmet', prompt: 'World War One doughboy steel pot helmet in olive drab, round brim, 1917 infantry Brodie helmet' },
      { label: 'Roman legionnaire galea', prompt: 'Roman legionnaire galea helmet with cheek guards and neck guard, lorica legionary standard headgear' },
    ],
  },
  {
    label: '👒 Hats & Classic',
    options: [
      { label: 'Top hat', prompt: 'Tall black silk top hat with satin ribbon band, formal Victorian gentleman headwear' },
      { label: 'Sombrero', prompt: 'Large wide-brimmed Mexican sombrero with colorful embroidered patterns and decorative trim' },
      { label: 'Ushanka fur hat', prompt: 'Russian ushanka winter fur hat with ear flaps, thick fur lining, Soviet cold weather gear' },
      { label: 'Safari pith helmet', prompt: 'White colonial safari pith helmet with chin strap, tropical sun protection, explorer headwear' },
      { label: 'Straw farmer hat', prompt: 'Wide-brimmed straw farmer hat, woven natural straw with leather chin cord, countryside look' },
      { label: 'Bowler derby hat', prompt: 'Classic black bowler derby hat with curved brim and rounded dome crown, English gentleman' },
      { label: 'Cowboy ten-gallon', prompt: 'Classic ten-gallon cowboy hat in tan felt with leather band, wide curled brim, Texas rancher style' },
      { label: 'Beret angled', prompt: 'Classic French beret in dark navy angled dramatically, artist or resistance fighter continental style' },
      { label: 'Tricorne pirate hat', prompt: 'Classic three-cornered tricorne hat in black with gold trim, pirate captain or colonial era headwear' },
      { label: 'Jester tri-point cap', prompt: 'Medieval court jester tri-point hat with bells on each point, motley colored fabric, fool cap' },
    ],
  },
  {
    label: '👑 Crowns & Royalty',
    options: [
      { label: 'Jeweled royal crown', prompt: 'Ornate gold royal crown studded with large rubies, sapphires, and diamonds, velvet interior, king' },
      { label: 'Golden laurel wreath', prompt: 'Ancient Roman golden laurel wreath crown, delicate gold leaves in circular band, Caesar emperor' },
      { label: 'Pharaoh nemes headdress', prompt: 'Egyptian pharaoh striped nemes headdress in blue and gold with cobra uraeus on forehead' },
      { label: 'Ice queen tiara', prompt: 'Crystalline ice queen tiara with frozen icicle points and blue gemstones, frost magic royalty' },
      { label: 'Dark lord iron crown', prompt: 'Dark spiked iron crown with jagged points, dark metal with red glowing gems, evil lord headwear' },
      { label: 'Flower wreath crown', prompt: 'Beautiful flower wreath crown with roses, daisies, and small wildflowers woven together, nature' },
      { label: 'Viking jarl circlet', prompt: 'Heavy Viking jarl silver circlet with knotwork interlace pattern, Norse chieftain status headband' },
      { label: 'Samurai daimyo war crown', prompt: 'Samurai daimyo war crown with family mon crest rising tall from a lacquered headpiece, feudal lord' },
      { label: 'Aztec feathered headdress', prompt: 'Aztec emperor quetzal feathered headdress, enormous green plumes radiating outward, Moctezuma crown' },
      { label: 'Maharaja jeweled turban', prompt: 'Indian maharaja jeweled turban with kalgi aigrette brooch and ruby star burst, princely state royalty' },
    ],
  },
  {
    label: '🐉 Fantasy & Creature',
    options: [
      { label: 'Dragon horns', prompt: 'Large curved dragon horns growing from the head, scaled bone in dark grey, fantasy creature' },
      { label: 'Angel halo', prompt: 'Glowing golden angel halo floating above the head, bright divine ring of light, heavenly holy' },
      { label: 'Demon skull helmet', prompt: 'Demonic skull helmet with curved horns and red glowing eyes, hellish bone headgear' },
      { label: 'Unicorn horn', prompt: 'Single spiraling unicorn horn growing from the forehead, pearlescent white with rainbow shimmer' },
      { label: 'Antler deer rack', prompt: 'Large deer antler rack growing from the head, natural brown bone antlers, forest spirit' },
      { label: 'Ram curved horns', prompt: 'Massive curved ram horns spiraling from the sides of the head, thick ridged bone, satyr' },
      { label: 'Mermaid crown of coral', prompt: 'Mermaid ocean crown woven from red coral branches with pearl accents, deep sea royalty headdress' },
      { label: 'Phoenix flame crest', prompt: 'Phoenix fire crest rising from the crown, tall flame-shaped living fire, firebird reincarnation energy' },
      { label: 'Medusa snake crown', prompt: 'Medusa head of living snakes writhing upward as hair, hissing serpents radiating, Greek gorgon curse' },
      { label: 'Elf leaf ear tips', prompt: 'Long elegant pointed elf ear tips rising at the sides, Tolkien Legolas high elf pointed ear anatomy' },
    ],
  },
  {
    label: '🤖 Sci-Fi & Tech',
    options: [
      { label: 'Robot dome head', prompt: 'Chrome robot dome helmet head covering, smooth metallic head with LED eye strips, android' },
      { label: 'Cyberpunk neural implant', prompt: 'Cyberpunk brain neural implant hardware on shaved head, wires, ports, and LED status lights' },
      { label: 'Astronaut fish bowl', prompt: 'Clear glass astronaut space helmet bubble, round fishbowl with reflection, space suit headgear' },
      { label: 'Antenna headband', prompt: 'Alien antenna headband with two bobbing antenna stalks on springs, cute alien costume piece' },
      { label: 'Mech pilot helmet', prompt: 'Mech pilot enclosed helmet with heads-up display visor, armored flight helmet, gundam style' },
      { label: 'AI brain chip visor', prompt: 'Sleek AI augmentation visor across the forehead with holographic data readout, transhumanist tech' },
      { label: 'Tactical HUD helmet', prompt: 'Military tactical helmet with full heads-up display visor overlay, targeting reticle, soldier AR system' },
      { label: 'VR headset full', prompt: 'Full VR headset covering the eyes, black visor with status lights, metaverse portal device' },
      { label: 'Scanner eye implant', prompt: 'Robotic scanner eye implant replacing one eye, red targeting reticle, Terminator vision mode' },
      { label: 'Hologram projector', prompt: 'Hologram projector unit on the head, beaming a small 3D holographic display above, portable hard-light projector' },
    ],
  },
  {
    label: '🎪 Wild & Absurd',
    options: [
      { label: 'Bucket on head', prompt: 'Metal bucket turned upside down on the head as a makeshift helmet, improvised headgear' },
      { label: 'Traffic cone', prompt: 'Orange traffic cone worn on the head as a pointy hat, road construction cone party look' },
      { label: 'Pineapple hat', prompt: 'Whole pineapple fruit sitting on top of the head as a hat, tropical fruit headwear' },
      { label: 'Fish head hat', prompt: 'Large fish head worn as a hat, flopping fish with open mouth perched on head, absurd comedy' },
      { label: 'Shark fin', prompt: 'Grey shark dorsal fin attached to the top of the head, sticking straight up, Jaws reference' },
      { label: 'Toilet plunger', prompt: 'Rubber toilet plunger stuck to the top of the head, suction cup attached, comedy prop' },
      { label: 'Aquarium fishbowl', prompt: 'Fishbowl aquarium with live fish swimming inside placed over the head, office fish tank hat' },
      { label: 'Birdcage with bird', prompt: 'Ornate birdcage placed over the head with a small cartoon bird perched inside, trapped in elegance' },
      { label: 'Potted plant head', prompt: 'Terracotta pot with a growing plant on the head, soil spilling slightly, living hat ecosystem' },
      { label: 'Lampshade party hat', prompt: 'Lampshade worn as a party hat tilted at an angle, classic I have had too much fun indicator' },
      { label: 'Globe head', prompt: 'A globe of the Earth balanced on the head, tiny planet Earth hat, Atlas holding up the world' },
    ],
  },
  {
    label: '🌍 Cultural & Traditional',
    options: [
      { label: 'Native war bonnet', prompt: 'Traditional Native American feathered war bonnet with long trailing eagle feathers, chief headdress' },
      { label: 'Turkish fez', prompt: 'Red Turkish fez hat with black tassel, flat-topped cylindrical ottoman headwear' },
      { label: 'Russian ushanka', prompt: 'Russian military ushanka fur hat with Soviet star emblem, ear flaps up, winter army hat' },
      { label: 'Viking horned helm', prompt: 'Iconic Viking horned helmet with two curved horns, iron and leather Norse warrior headgear' },
      { label: 'Chinese conical hat', prompt: 'Traditional Chinese conical straw hat, wide pointed cone shape, rice paddy farmer hat' },
      { label: 'Scottish tam o\'shanter', prompt: 'Scottish tam o\'shanter beret with pompom on top, tartan plaid fabric, Highland bonnet' },
      { label: 'Zulu warrior headdress', prompt: 'Zulu warrior leopard skin headband with feather plumes and isicoco head ring, Natal warrior tradition' },
      { label: 'Sikh dastar turban', prompt: 'Sikh dastar turban in royal blue with steel Khanda chakkar pin, warrior saint Khalsa pride' },
      { label: 'Bedouin keffiyeh', prompt: 'Bedouin keffiyeh headscarf in red and white check pattern with black agal cord, desert nomad headwear' },
      { label: 'Noh theater mask', prompt: 'Japanese Noh theater mask with serene carved expression, lacquered white face, classical drama headwear' },
    ],
  },
  {
    label: '💀 Dark & Horror',
    options: [
      { label: 'Skull bone helmet', prompt: 'Helmet carved from a large animal skull, bone white with hollow eye sockets, death warrior' },
      { label: 'Witch pointed hat', prompt: 'Classic witch pointed hat in black with wide brim, buckle band, Halloween witchcraft' },
      { label: 'Plague doctor hood', prompt: 'Black plague doctor hood and mask with long pointed beak, medieval pandemic outfit' },
      { label: 'Ghostly floating crown', prompt: 'Ethereal transparent ghostly crown floating above the head, spectral glowing spirit crown' },
      { label: 'Spider web veil', prompt: 'Black spider web lace veil draped over the head, Gothic spider silk with tiny spiders' },
      { label: 'Pumpkin head carved', prompt: 'Carved jack-o-lantern pumpkin on the head with glowing triangle eyes and mouth, Halloween' },
      { label: 'Frankenstein neck bolts', prompt: 'Frankensteins monster neck bolt temples, deep green skin, flat-top head with visible stitching' },
      { label: 'Gas mask horror', prompt: 'WWII gas mask respirator with bug-eye lenses and corrugated hose, post-apocalyptic horror headgear' },
      { label: 'Clown paint melting', prompt: 'Evil clown makeup melting and dripping, red and white greasepaint running, Pennywise creepy' },
      { label: 'Scarecrow burlap sack', prompt: 'Burlap sack head with crude stitched face, button eyes and sewn smile, scarecrow awakened horror' },
    ],
  },
  {
    label: '🏋️ Sport & Activity',
    options: [
      { label: 'Football helmet', prompt: 'American football helmet with face cage guard and team decal, matte finish, NFL style' },
      { label: 'Boxing headguard', prompt: 'Red leather boxing headguard with cheek protectors and chin strap, sparring protection' },
      { label: 'Cycling aero helmet', prompt: 'Aerodynamic cycling time-trial helmet with pointed tail, sleek ventilated road bike helmet' },
      { label: 'Ski helmet with goggles', prompt: 'White ski helmet with attached orange mirror goggles on the forehead, winter sport gear' },
      { label: 'Scuba diving mask', prompt: 'Scuba diving full face mask with breathing regulator, underwater diving equipment' },
      { label: 'Baseball batting helmet', prompt: 'Baseball batting helmet with one ear flap, glossy team color, MLB batter protection' },
      { label: 'Lacrosse helmet cage', prompt: 'Lacrosse helmet with full cage face guard, ventilated shell, college lacrosse head protection' },
      { label: 'Polo helmet mallet', prompt: 'Polo player white helmet with chin strap, equestrian polo mallet tucked in, horse sport headwear' },
      { label: 'Cricket whites helmet', prompt: 'Cricket batting helmet with face grille, white cap below, test match cricket protective headgear' },
      { label: 'Motocross full face', prompt: 'Motocross full-face helmet with peak visor, bright graphic livery, off-road dirt bike racing helmet' },
    ],
  },
  {
    label: '🍔 Food & Object',
    options: [
      { label: 'Cheese wheel hat', prompt: 'Large cheese wheel wedge hat on the head, yellow cheddar with holes, Packers cheesehead style' },
      { label: 'Watermelon helmet', prompt: 'Carved-out watermelon half worn as a helmet, green rind outside with red fruit visible' },
      { label: 'Spaghetti bowl hat', prompt: 'Bowl of spaghetti and meatballs balanced on the head, pasta dangling over the sides' },
      { label: 'Birthday cake hat', prompt: 'Tiered birthday cake with frosting and lit candles perched on the head, party celebration' },
      { label: 'Popcorn bucket hat', prompt: 'Large movie theater popcorn bucket on the head, overflowing popped kernels, cinema snack' },
      { label: 'Ice cream cone hat', prompt: 'Large ice cream waffle cone on the head with scoops of colorful ice cream and sprinkles' },
      { label: 'Hamburger bun hat', prompt: 'Sesame seed hamburger bun on the head with lettuce and cheese slipping out, fast food headwear' },
      { label: 'Sushi roll crown', prompt: 'Giant maki sushi roll on the head, nori seaweed outer, rice visible, salmon topping, Japanese crown' },
      { label: 'Taco shell helmet', prompt: 'Crunchy taco shell worn as a helmet, lettuce and cheese falling out the sides, Mexican food hat' },
      { label: 'Sunflower head', prompt: 'Giant sunflower growing from the head instead of hair, yellow petals radiating and dark seed center' },
      { label: 'Snowglobe hat', prompt: 'Snow globe placed over the head as a helmet, winter scene inside with snow falling, glass dome world' },
    ],
  },
];

const BACKGROUND_CREATE: AIStyleFamily[] = [
  {
    label: '🌆 City & Urban',
    options: [
      { label: 'Tokyo neon alley', prompt: 'Narrow Tokyo alley at night, neon shop signs on left and right sides in pink and blue, Japanese lanterns on edges, open center, flat color cartoon drawing' },
      { label: 'Cyberpunk rain street', prompt: 'Dark cyberpunk city street, neon signs and buildings on left and right sides, rain lines, puddles on ground, open center, flat cartoon illustration' },
      { label: 'NYC rooftop sunset', prompt: 'City rooftop at sunset, buildings on left and right edges, warm orange sky with simple clouds at top, open center, flat cartoon drawing style' },
      { label: 'London fog alley', prompt: 'Foggy London cobblestone alley, brick buildings on left and right, street lamp on one side, thick fog, open center, flat cartoon illustration' },
      { label: 'Paris rooftop café', prompt: 'Paris rooftop with small café table on one side, Eiffel Tower in far background, iron railings on edges, open center, flat cartoon drawing' },
      { label: 'Las Vegas strip', prompt: 'Las Vegas strip at night, casino signs and bright lights on left and right, neon glow, open center, flat cartoon illustration' },
      { label: 'Hong Kong harbour', prompt: 'Hong Kong harbour at night, skyscraper towers on left and right edges, neon signs and reflections on water, open center, flat cartoon drawing' },
      { label: 'Miami art deco strip', prompt: 'Miami Beach art deco hotel strip, pastel facades with curved signs on left and right, palm trees, open center, flat cartoon illustration' },
      { label: 'Shibuya crossing', prompt: 'Tokyo Shibuya pedestrian crossing, tall buildings and neon billboards on left and right, white crossing lines, open center, flat cartoon drawing' },
      { label: 'New Orleans French Quarter', prompt: 'New Orleans French Quarter, wrought iron balconies on buildings left and right, gas lanterns, jazz bar sign, open center, flat cartoon illustration' },
      { label: 'Chicago elevated train', prompt: 'Chicago Loop el train platform, steel girder structure on left and right, city skyline through gaps, open center, flat cartoon drawing' },
      { label: 'Seoul PC bang', prompt: 'Korean PC bang gaming cafe, rows of glowing monitors on left and right, neon signage, dark room, open center, flat cartoon drawing' },
    ],
  },
  {
    label: '🏝️ Nature & Wild',
    options: [
      { label: 'Tropical beach sunset', prompt: 'Tropical beach at sunset, palm trees on left and right edges, orange sky at top, turquoise water and sand at bottom, open center, flat cartoon illustration' },
      { label: 'Coral reef underwater', prompt: 'Underwater coral reef, colorful corals on left and right edges in orange and purple, small fish on sides, blue water fill, open center, flat cartoon style' },
      { label: 'Dense jungle', prompt: 'Dense tropical jungle, giant fern leaves and vines on left and right edges, exotic flowers on sides, green canopy at top, open center, flat cartoon illustration' },
      { label: 'Cherry blossom garden', prompt: 'Japanese zen garden, cherry blossom tree on one side, raked sand and rocks on edges, soft dawn sky, open center, flat cartoon drawing' },
      { label: 'Waterfall cave', prompt: 'Cave behind a waterfall, rocky walls on left and right, water curtain in front, moss and ferns on edges, open center, flat cartoon illustration' },
      { label: 'Northern lights tundra', prompt: 'Arctic tundra at night, snowy ground, green and purple aurora borealis in sky, pine trees on edges, open center, flat cartoon drawing' },
      { label: 'Sahara desert dunes', prompt: 'Sahara desert dunes, tall sand dunes on left and right with ripple patterns, blazing sun, open center, flat cartoon illustration' },
      { label: 'Rocky mountain peak', prompt: 'Rocky mountain summit, jagged snow-capped peaks on left and right edges, eagles soaring, clear blue sky, open center, flat cartoon style' },
      { label: 'Deep cave stalactites', prompt: 'Deep underground cave, stalactites hanging from ceiling edges, glowing mushrooms on sides, dark void, open center, flat cartoon illustration' },
      { label: 'Bamboo forest path', prompt: 'Dense bamboo forest, tall green bamboo stalks on left and right, dappled light filtering down, mist, open center, flat cartoon style' },
      { label: 'Lava field Hawaii', prompt: 'Hawaiian lava field, black cooled lava ground, ferns and ohia trees on edges, red glow at horizon, open center, flat cartoon drawing' },
      { label: 'Giant sequoia grove', prompt: 'Giant sequoia forest, enormous redwood trunks on left and right dwarfing everything, golden light, open center, flat cartoon illustration' },
    ],
  },
  {
    label: '🏰 Historical & Fantasy',
    options: [
      { label: 'Castle throne room', prompt: 'Medieval castle throne room, stone walls with torches on left and right sides, red carpet on floor, golden throne in far back, open center, flat cartoon drawing' },
      { label: 'Egyptian temple', prompt: 'Ancient Egyptian temple, hieroglyphic stone columns on left and right, torches on walls, sandstone floor, open center, flat cartoon style' },
      { label: 'Greek ruins', prompt: 'Greek temple ruins, marble columns on left and right, blue sky at top, olive trees on edges, open center, flat cartoon style' },
      { label: 'Viking longhouse', prompt: 'Viking longhouse interior, wooden beams and shields on walls left and right, fire pit in center back, open center, flat cartoon drawing' },
      { label: 'Wizard library', prompt: 'Grand wizard library interior, tall bookshelves on left and right walls, floating candles, magical glow, open center, flat cartoon drawing' },
      { label: 'Samurai dojo', prompt: 'Japanese samurai dojo training hall, wooden walls with hanging katanas on sides, tatami floor, open center, flat cartoon illustration' },
      { label: 'Medieval dungeon', prompt: 'Stone medieval dungeon, iron-barred cells on left and right walls, torch sconces, chains hanging, open center, flat cartoon drawing' },
      { label: 'Pirate ship captain cabin', prompt: 'Pirate captain cabin interior, treasure map on one wall, cannon ports on sides, lanterns swinging, open center, flat cartoon style' },
      { label: 'Colosseum arena floor', prompt: 'Roman Colosseum arena floor, stone wall with arched tunnels on left and right, sand floor, roaring crowd above, open center, flat cartoon illustration' },
      { label: 'Aztec pyramid temple', prompt: 'Aztec stepped pyramid temple, stone relief carvings on left and right columns, jungle below, open center, flat cartoon drawing' },
      { label: 'Wild West saloon', prompt: 'Wild West saloon interior, wooden bar on one side, piano in corner, wanted posters on walls, swing doors, open center, flat cartoon style' },
      { label: 'Ming dynasty palace gate', prompt: 'Chinese Ming dynasty palace gate, red lacquered pillars on left and right, dragon carved lintels, golden roof edge, open center, flat cartoon illustration' },
    ],
  },
  {
    label: '🚀 Sci-Fi & Space',
    options: [
      { label: 'Spaceship cockpit', prompt: 'Futuristic spaceship cockpit interior, control panels on left and right edges, starfield through viewport in back, open center, flat cartoon illustration' },
      { label: 'Moon surface', prompt: 'Lunar surface, grey craters on left and right sides, Earth visible in top corner, black starry sky, open center, flat cartoon illustration' },
      { label: 'Mars colony', prompt: 'Mars colony base, red rocky terrain on edges, dome habitats on sides, rust-colored sky at top, open center, flat cartoon style' },
      { label: 'Space nebula', prompt: 'Deep space nebula, swirling purple and pink gas clouds on edges, scattered stars, dark void center, flat cartoon illustration' },
      { label: 'Asteroid field', prompt: 'Asteroid field in space, grey and brown space rocks floating on edges, distant stars, dark space, open center, flat cartoon drawing' },
      { label: 'Alien planet jungle', prompt: 'Alien planet with bioluminescent plants on edges, glowing mushrooms and strange flora, purple sky, open center, flat cartoon illustration' },
      { label: 'Space station ring', prompt: 'Space station rotating ring habitat, centrifuge corridor on left and right curving up, stars through windows, open center, flat cartoon drawing' },
      { label: 'Warp drive tunnel', prompt: 'Warp drive star tunnel, white light streaks from star field stretching on left and right, blue tunnel center, open center, flat cartoon style' },
      { label: 'Alien hive interior', prompt: 'Alien xenomorph hive interior, ribbed resin walls on left and right, eggs on ground edges, dark organic, open center, flat cartoon illustration' },
      { label: 'Martian canyon', prompt: 'Valles Marineris Martian canyon, red rock walls towering on left and right, dust haze at horizon, open center, flat cartoon drawing' },
      { label: 'Gas giant clouds', prompt: 'Jupiter gas giant cloud layer, swirling orange and brown storm bands on left and right, no ground, open center, flat cartoon illustration' },
      { label: 'Derelict ghost ship', prompt: 'Derelict ghost spaceship corridor, torn hull panels on left and right, stars visible through gaps, fog, open center, flat cartoon drawing' },
    ],
  },
  {
    label: '🏠 Indoor Scenes',
    options: [
      { label: 'Cozy cabin fireplace', prompt: 'Wooden cabin interior, stone fireplace on one side, bookshelves on other side, warm orange glow, open center floor, flat cartoon drawing' },
      { label: 'Trading desk monitors', prompt: 'Trading room, monitors with green charts on left and right sides, desk on bottom edge, dark room lit by screens, open center, flat cartoon style' },
      { label: 'Retro arcade room', prompt: 'Retro arcade room, gaming cabinets on left and right sides, colorful pixel screens glowing, purple ambient light, open center floor, flat cartoon style' },
      { label: 'Grand library', prompt: 'Grand library interior, tall bookshelves on left and right walls, reading lamp on side, warm lighting, open center, flat cartoon drawing' },
      { label: 'Jazz lounge', prompt: 'Dim jazz lounge, leather booth seating on sides, stage with microphone in back, blue mood lighting, open center, flat cartoon illustration' },
      { label: 'Ramen shop kitchen', prompt: 'Japanese ramen shop interior, kitchen counter on one side, menu boards and lanterns on edges, steamy warm, open center, flat cartoon drawing' },
      { label: 'Server room data center', prompt: 'Data center server room, blinking server racks on left and right, blue LED lights, cool air vents, open center, flat cartoon illustration' },
      { label: 'Recording studio booth', prompt: 'Recording studio booth, soundproof foam panels on left and right walls, microphone stand in one corner, open center, flat cartoon style' },
      { label: 'Interrogation room', prompt: 'Police interrogation room, two-way mirror on one wall, metal table on one side, single overhead bulb, open center, flat cartoon illustration' },
      { label: 'Observatory dome', prompt: 'Astronomical observatory interior, telescope on one side, dome opening to stars above, charts on walls, open center, flat cartoon illustration' },
      { label: 'Speakeasy bar', prompt: '1920s Prohibition speakeasy, brick walls with bottles on left and right, jazz stage in back, low light, open center, flat cartoon style' },
      { label: 'Museum diorama hall', prompt: 'Natural history museum hall, large display cases with dioramas on left and right walls, spotlights, open center, flat cartoon illustration' },
    ],
  },
  {
    label: '⚡ Action & Extreme',
    options: [
      { label: 'Volcano eruption', prompt: 'Volcano crater, dark rock walls on left and right, orange lava flowing on edges, red glow at top, open center, flat cartoon illustration' },
      { label: 'Thunderstorm', prompt: 'Dark thunderstorm sky, heavy rain, lightning bolt on one side, storm clouds at top, wind-blown trees on edges, open center, flat cartoon drawing' },
      { label: 'Boxing ring', prompt: 'Boxing ring, ropes and corner posts on left and right, spotlight from top, crowd silhouettes on edges, open center, flat cartoon style' },
      { label: 'Gladiator arena', prompt: 'Roman gladiator arena, stone colosseum walls on left and right, roaring crowd at top, sandy floor, open center, flat cartoon illustration' },
      { label: 'Zombie apocalypse street', prompt: 'Post-apocalyptic zombie street, abandoned cars and broken buildings on left and right, dark sky, debris on edges, open center, flat cartoon drawing' },
      { label: 'Pirate battle at sea', prompt: 'Pirate ship deck during sea battle, ship railings on left and right, cannon smoke, stormy ocean, open center, flat cartoon illustration' },
      { label: 'Tornado alley', prompt: 'Tornado alley chase scene, dark storm wall on one side, debris flying on edges, emergency vehicle lights, open center, flat cartoon drawing' },
      { label: 'Nuclear explosion', prompt: 'Nuclear bomb detonation, mushroom cloud rising on one side, blast wave spreading on edges, orange glow, open center, flat cartoon illustration' },
      { label: 'Asteroid impact crater', prompt: 'Fresh asteroid impact crater, scorched rock walls on left and right, smoke rising, fiery glow at edges, open center, flat cartoon drawing' },
      { label: 'Wildfire inferno', prompt: 'Raging wildfire forest, burning tree trunks on left and right, orange flames consuming edges, smoke sky, open center, flat cartoon illustration' },
      { label: 'MMA octagon cage', prompt: 'MMA octagon cage, chain-link fence on left and right, corner stools in corners, bright spotlights, open center, flat cartoon drawing' },
      { label: 'NASCAR track straight', prompt: 'NASCAR superspeedway straight, crash barrier walls on left and right, grandstand above, tarmac below, open center, flat cartoon illustration' },
    ],
  },
  {
    label: '🌀 Abstract & Surreal',
    options: [
      { label: 'Vaporwave grid', prompt: 'Retro vaporwave grid landscape, neon pink and cyan grid lines, setting sun, palm trees on edges, open center, flat cartoon style' },
      { label: 'Floating island', prompt: 'Magical floating island, green grass on top, blue sky with simple clouds on sides, open center, flat cartoon drawing' },
      { label: 'Crystal cave', prompt: 'Crystalline cave interior, large amethyst and quartz crystal formations on left and right walls, purple glow, open center, flat cartoon illustration' },
      { label: 'Neon tunnel', prompt: 'Infinite neon light tunnel, glowing ring lights in pink and blue receding into distance, dark void center, flat cartoon style' },
      { label: 'Geometric void', prompt: 'Abstract geometric void, floating polyhedron shapes on edges, dark space with colored light beams, open center, flat cartoon drawing' },
      { label: 'Infinite mirror room', prompt: 'Infinite mirror room, reflective walls on all sides creating endless reflections, LED lights, open center, flat cartoon illustration' },
      { label: 'Escher staircase', prompt: 'M.C. Escher impossible staircase, stairs going up on left and down on right in an endless loop, open center, flat cartoon illustration' },
      { label: 'Mandelbrot fractal zoom', prompt: 'Mandelbrot fractal deep zoom, infinite recursive fractal patterns on left and right edges, electric colors, open center, flat cartoon style' },
      { label: 'Color spectrum void', prompt: 'Rainbow color spectrum void, spectrum bands fanning on left and right edges, pure white center, open center, flat cartoon drawing' },
      { label: 'Recursive portal loop', prompt: 'Infinite recursive portal loop, portals within portals shrinking on left and right, orange and blue ring frames, open center, flat cartoon illustration' },
      { label: 'Zero gravity bubble', prompt: 'Zero gravity environment, floating objects on left and right edges, no clear up or down, bubbles drifting, open center, flat cartoon drawing' },
      { label: 'Dreamscape clouds', prompt: 'Dream logic cloudscape, giant floating cloud pillars on left and right, pastel pink and lavender sky, open center, flat cartoon illustration' },
    ],
  },
  {
    label: '💰 Crypto & Meme',
    options: [
      { label: 'Stonks trading floor', prompt: 'Stock exchange trading floor, screens with green charts on walls left and right, ticker tape, trading desks on edges, open center, flat cartoon illustration' },
      { label: 'Mining rig warehouse', prompt: 'Crypto mining warehouse, rows of GPU mining rigs on left and right with blinking lights, cables, server racks, open center, flat cartoon drawing' },
      { label: 'Lambo garage', prompt: 'Luxury garage with Lamborghini sports car on one side, polished floor, neon lighting on walls, open center, flat cartoon illustration' },
      { label: 'Diamond vault', prompt: 'Bank vault interior, thick vault door on one side, gold bars and diamonds stacked on edges, steel walls, open center, flat cartoon style' },
      { label: 'Dumpster fire alley', prompt: 'Dark back alley with literal dumpster on fire on one side, brick walls, trash bags on edges, night sky, open center, flat cartoon drawing' },
      { label: 'NFT gallery hall', prompt: 'Modern NFT art gallery, framed digital art on walls left and right, spotlight lighting, polished floor, open center, flat cartoon illustration' },
      { label: 'Crypto whale office', prompt: 'Crypto whale home office, multiple screens showing charts on left and right, Lamborghini poster, pizza boxes, open center, flat cartoon drawing' },
      { label: 'Moon mission celebration', prompt: 'Crypto moon mission rocket launch, launchpad on one side, crowd celebrating on edges, rocket exhaust, open center, flat cartoon illustration' },
      { label: 'Bear market soup kitchen', prompt: 'Bear market soup kitchen line, sad traders in line on left and right, grey sky, empty wallets on edges, open center, flat cartoon style' },
      { label: 'Rug pull trapdoor', prompt: 'Rug pull moment, rug being pulled from under everything on left and right, falling coins on edges, open center, flat cartoon drawing' },
      { label: 'Diamond hands vault', prompt: 'Diamond hands vault interior, diamond gem walls on left and right shimmering, diamond emoji on floor, open center, flat cartoon drawing' },
      { label: 'Meme coin rocket', prompt: 'Meme coin rocket interior cockpit, doge and pepe stickers on left and right walls, moon visible ahead, open center, flat cartoon illustration' },
    ],
  },
  {
    label: '🎪 Entertainment',
    options: [
      { label: 'Concert stage', prompt: 'Concert stage, speakers and light rigs on left and right, crowd silhouettes below, spotlights from top, open center stage, flat cartoon illustration' },
      { label: 'Movie theater', prompt: 'Movie theater interior, rows of red seats on edges, large screen in back, dark room with projector light, open center, flat cartoon drawing' },
      { label: 'Sports stadium', prompt: 'Sports stadium, bleacher seats with crowd on left and right, bright floodlights at top, green field below, open center, flat cartoon style' },
      { label: 'Theme park', prompt: 'Colorful theme park, roller coaster tracks on one side, ferris wheel on other, carnival lights on edges, open center, flat cartoon illustration' },
      { label: 'Bowling alley', prompt: 'Retro bowling alley, lanes on left and right with pins at end, neon scoring screens above, polished wood floor, open center, flat cartoon drawing' },
      { label: 'Rooftop pool party', prompt: 'Rooftop pool party at sunset, pool edge on one side, lounge chairs and palm trees on edges, city skyline behind, open center, flat cartoon illustration' },
      { label: 'Escape room puzzle', prompt: 'Escape room interior, clue boards and locked boxes on left and right walls, countdown clock visible, open center, flat cartoon drawing' },
      { label: 'Retro game show set', prompt: 'Retro TV game show set, colorful prize doors on left and right, spinning wheel on one side, neon sign, open center, flat cartoon illustration' },
      { label: 'Kabuki theater stage', prompt: 'Japanese kabuki theater stage, painted pine tree scenery on left and right, hanamichi walkway, lanterns, open center, flat cartoon style' },
      { label: 'Drive-in movie screen', prompt: 'Drive-in movie theater, cars on left and right edges, giant white screen in back, speaker poles, dusk sky, open center, flat cartoon drawing' },
      { label: 'Comedy club stage', prompt: 'Stand-up comedy club stage, brick wall backdrop on one side, small tables with lamps on edges, spotlight, open center, flat cartoon illustration' },
    ],
  },
];

// --- Assemble the full catalog ---

export const AI_PRESET_CATALOG: Partial<Record<AICategory, AICategoryPresets>> = {
  clothes: {
    enhance: [...UNIVERSAL_ENHANCE, ...CLOTHES_ENHANCE],
    create_new: CLOTHES_CREATE,
  },
  head: {
    enhance: [...UNIVERSAL_ENHANCE, ...HEAD_ENHANCE],
    create_new: HEAD_CREATE,
  },
  background: {
    create_new: BACKGROUND_CREATE,
  },
};

// --- Randomizer ---

export function getRandomPreset(
  category: AICategory,
  mode: 'enhance' | 'create_new',
): { family: AIStyleFamily; option: { label: string; prompt: string } } | null {
  const presets = AI_PRESET_CATALOG[category];
  if (!presets) return null;
  const families = mode === 'enhance' ? presets.enhance : presets.create_new;
  if (!families || families.length === 0) return null;

  const family = families[Math.floor(Math.random() * families.length)];
  const option = family.options[Math.floor(Math.random() * family.options.length)];
  return { family, option };
}
