// src/components/generator/ai/AIEnhanceLightbox.tsx

import { Lightbox } from '@/components/ui/Lightbox';
import { useAIEnhance } from '@/contexts/AIEnhanceContext';
import { AICategoryPicker } from './AICategoryPicker';
import { AIPromptBuilder } from './AIPromptBuilder';
import { AILoadingState } from './AILoadingState';
import { AIResultComparison } from './AIResultComparison';
import { AICreditsDisplay } from './AICreditsDisplay';
import { ArrowLeft, Info } from 'lucide-react';
import type { AIWizardStep } from '@/types/aiEnhance';

interface AIEnhanceLightboxProps {
  /** Base64 data URL of the current canvas image to enhance */
  currentImage: string | null;
}

const STEP_ORDER: AIWizardStep[] = ['category', 'prompt', 'loading', 'result'];

export function AIEnhanceLightbox({ currentImage }: AIEnhanceLightboxProps) {
  const {
    isLightboxOpen,
    closeLightbox,
    wizardStep,
    setWizardStep,
    selectedCategory,
    selectedMode,
    isEnhancing,
    enhancedImage,
    handlePromptBack,
  } = useAIEnhance();

  // Always use the latest image (enhanced or original) for both display and AI input.
  // If the user has accepted a previous enhancement (e.g., background), subsequent
  // enhancements (e.g., clothing) must build on that result to preserve prior work.
  const activeImage = enhancedImage ?? currentImage;

  const handleBack = () => {
    if (wizardStep === 'result') {
      setWizardStep('prompt');
    } else if (wizardStep === 'prompt') {
      // Delegate to context — it knows the prompt sub-step
      handlePromptBack();
    }
  };

  const showBack = (wizardStep === 'prompt' || wizardStep === 'result') && !isEnhancing;
  const currentStepIndex = STEP_ORDER.indexOf(wizardStep);

  // Dynamic title
  const categoryLabel = selectedCategory
    ? selectedCategory.charAt(0).toUpperCase() + selectedCategory.slice(1)
    : '';
  const displayTitle =
    wizardStep === 'category'
      ? 'Enhance with AI'
      : wizardStep === 'prompt'
        ? selectedMode === 'create_new'
          ? `New ${categoryLabel}`
          : `${categoryLabel} Style`
        : wizardStep === 'loading'
          ? 'Creating...'
          : 'Your Enhancement';

  // Custom header: [Back + Credits] [Title + dots] [Info]  (close button added by Lightbox)
  const header = (
    <div className="ai-wizard-header">
      {/* Left: back button + credits */}
      <div className="ai-wizard-header-left">
        {showBack ? (
          <button
            className="ai-wizard-back"
            onClick={handleBack}
            aria-label="Go back"
          >
            <ArrowLeft size={16} />
            <span>Back</span>
          </button>
        ) : null}
        <AICreditsDisplay />
      </div>

      {/* Center: title + step dots */}
      <div className="ai-wizard-header-center">
        <h2 className="ai-wizard-title">{displayTitle}</h2>
        <div className="ai-wizard-steps">
          {STEP_ORDER.map((step, i) => (
            <div
              key={step}
              className={`ai-wizard-dot ${
                i === currentStepIndex
                  ? 'ai-wizard-dot--active'
                  : i < currentStepIndex
                    ? 'ai-wizard-dot--done'
                    : ''
              }`}
            />
          ))}
        </div>
      </div>

      {/* Right: info tooltip */}
      <div className="ai-wizard-header-right">
        <div className="ai-info-tooltip-wrapper">
          <button className="ai-info-btn" aria-label="AI disclaimer info">
            <Info size={14} />
          </button>
          <div className="ai-info-tooltip">
            AI enhancements are generated by artificial intelligence. Each prompt has been carefully crafted, but results may vary. If the result isn&apos;t what you expected, try again or pick a different style. No credits are charged for results you discard.
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <Lightbox
      isOpen={isLightboxOpen}
      onClose={closeLightbox}
      headerContent={header}
      size="xl"
    >
      {/* Accent line */}
      <div className="ai-wizard-accent" />

      {/* Wizard steps */}
      <div className="flex flex-col gap-2 sm:gap-4 mt-1 sm:mt-2">
        {wizardStep === 'category' && (
          <AICategoryPicker currentImage={activeImage} />
        )}
        {wizardStep === 'prompt' && (
          <AIPromptBuilder currentImage={activeImage} />
        )}
        {wizardStep === 'loading' && (
          <AILoadingState currentImage={activeImage} />
        )}
        {wizardStep === 'result' && (
          <AIResultComparison currentImage={activeImage} />
        )}
      </div>
    </Lightbox>
  );
}
